### ISSUE TITLE
Wrong commit message when a PR from resource `pullrequests` has 2 or more commits

### ISSUE THREAD

**Issue by macedogm** [updatecli/updatecli#1005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a PR is made from a resource `pullrequests` and it has 2 or more commits from multiple `targets`, the commit message for the second and afterwards commits is ignored and it's always equal as the first commit.

For example, see PR https://github.com/rancher/rancher/pull/39696 and the 3 commits:
1. https://github.com/rancher/rancher/pull/39696/commits/53f7944f751afe2fe25e4d32139f2ed782729adf
2. https://github.com/rancher/rancher/pull/39696/commits/08380e994f72cf9987365fb4044b9562500c9667
3. https://github.com/rancher/rancher/pull/39696/commits/48c7559204b23eeedbf342d11b9af3a0562d6e21

Each commit updates a different file, but the message for commits 2 and 3 is the same as commit 1.

This happens, because the commit message is not a new variable for each commit. It's currently being update as a global variable.

https://github.com/updatecli/updatecli/blob/0a4f057cb7732f26feab143e7c85791c174e753b/pkg/plugins/scms/git/commit/main.go#L104-L113

Additionally, if the commit title is set in the configuration, but body is not set, then the commit message will be broken. It will use the configured commit title, but the body from the generated commit itself. For example:

```
chore: Bump rancher/shell image version
... ash.sh e7a1cc6a9b414787b3dc8937d614dd30649864ec"

Made with ❤️️ by updatecli
```

### Expected Behavior

Each commit must have its own commit message.

### Steps To Reproduce

See PR https://github.com/rancher/rancher/pull/39696 and the used configuration in https://github.com/rancherlabs/updatecli-automation/blob/34a0cc4687c8c069feaed457cf843c6cbd6a8507/updatecli/updatecli.d/rancher/shell/rancher/v2.7/shell.yaml#L49-L76.

### Environment

```markdown
- OS: Mac (arm64) and Ubuntu 22.04 (amd64)
- updatecli: v0.38.0
```

**Comment by macedogm** [comment]
@olblak this can also be closed with https://github.com/updatecli/updatecli/pull/1006.

**Comment by dduportal** [comment]
Closing as requested. Please note that 0.38.1 is currently being released with your fixes. Many thanks for the contribution!
