### ISSUE TITLE
YAML multiline folded block scalars broken by apply

### ISSUE THREAD

**Issue by alxgomz** [updatecli/updatecli#1028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using YAML target on a file which contains multi-line folded block scalars (`>-`) renders a new YAML file with single-line scalar as shown in the diff below:

```diff
       JAVA_OPTS: >-
-        -XX:MinRAMPercentage=50
-        -XX:MaxRAMPercentage=80
-
+        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
     postgres:
```

### Expected Behavior

formatting of the scalar value should be identical to the input (if valid)

### Environment

```markdown
- OS: MacOSX
- updatecli: 0.39.0
```

### Anything else?

May be connected to #794

**Comment by olblak** [comment]
Thanks for reporting this issue.
This highlight that some effort is needed on the yaml resource

**Comment by olblak** [comment]
After some quick tests, it appears that https://github.com/updatecli/updatecli/pull/1333 would solve this issue
