### ISSUE TITLE
Feature Request: Redesign GitHub Pullrequest body

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1125]
### Is your feature request related to a problem?

A pullrequeset created by Updatecli doesn't provide usefull information when it changes more than one target such as https://github.com/olblak/updatecli-app-dashboard/pull/34

The problem is different pipeline can reuse the same pipeline, some have changelog, others not. And finally a pullrequest can change different type of information.

### Solution you'd like

Using html means that we can "easily" parse existing pullrequest body. By using the tag "id" we can specify hidden information to identify to which pipeline the information is related

## Template

```
<body>

    <h2 id="<pipeline_spec_checksum>"> Pipeline Name</h2>
    <!-- I am wondering if adding a field description to the pipeline spec so we could display it here with additional information-->

    Show Pipeline Reports

    <!-- For each target in a manifest-->
    <details><summary id="<target1_spec_checksum>"><h3>Target One Name</h3></summary>
        <details><summary><h4>Changelog</h4></summary>
        
        <!-- I am wondering if adding a field description to the resource spec so we could display it here-->
        
        ```
            Changelog output
        ```
        </details>
    </details>

    <!-- For each target in a manifest-->
    <details><summary id="<target1_spec_checksum>"><h3>Target Two Name</h3></summary>
        <details><summary><h4>Changelog</h4></summary>
        
        <!-- I am wondering if adding a field description to the resource spec so we could display it here-->
        
        ```
            Changelog output
        ```
        </details>
    </details>

    <!-- Show disclaimer-->>
</body>
```

## Example

<h2 id="asdfasdfasd">Update Golang Version used</h2>
<details><summary><h3>Update Golang used by go.mod</h3></summary>
<details><summary><h4>Changelog</h4></summary>
 
 ```
   This release fix bug XxX
  ```

</details>
</details>

<details><summary><h3>Update Golang used in Dockerfile</h3></summary>
</details>

<details><summary><h3>Update Golang used in Hugo</h3></summary>
</details>

### Alternatives you've considered

Considering that GitHub pullrequest accept both Markdown and Html, I considered using directly Markdown but after some quick search it appears easier to parse html and only edit the correct information based on the ID than using Markdown

### Anything else?

As we know the structure of the body in advance, we could simply use a xml parser to parse existing pullrequest body

**Comment by olblak** [comment]
I should be able to open a pullrequest soon

**Comment by dduportal** [comment]
@olblak as an updatecli user, I expect the following from the pull requests:

- The title should be clear:
  - Either the PR is about only one change (1 source), I expect something like "Bump <whatever> to <new version>". (Nice to have: "from <old version> to <new version>" but not mandatory)
  - Either the PR is what I call "a monster", then I expect the title to be specified by the manifest (and it would be the user's fault to maintain such a monster :D )
- The body should:
  - If the PR is about only one change, then:
    - Add a summary of the change (almost the same as the title)
    - "Release Note": either a link to the changelog and/or a foldable block quote of the changes
    - A section about "Updatecli" to explain this PR was created automatically, some contextual informations (links, eventually the PR provenance for instance)
  - If the PR is "a monster":
    - A summary of the change (almost the same as the title)
    - A list of the "changes" (would that mean the targets?). Could this be a table?
    - A foldable list of the "Release Note" with one per change (target?)
    - A section about "Updatecli" (etc.)

**Comment by olblak** [comment]
Thanks for the feedback.

> Either the PR is about only one change (1 source)

That's an interesting view that I didn't considered, usually I see project fetching one information and then transforming for different target such as Dockerfile/Yaml/File, readme.md, etc.  The first piece of information I am interested is identifying the target and the the information change. That being said in the current state we have changelog duplication 

> Either the PR is what I call "a monster"

To me, calling a PR a "monster" is a bit contemptuous :)
It's already user's fault to maintain the manifest.

When we craft a pullrequest body, all of information comes from the manifest maintained by a user.

For example, a pullrequest title is defined in the following order, with the first available information

1. Action title
2. Pipeline Title
3. First target title

Target information relies on target title and changelog associated to the its source.
As mentioned in https://github.com/updatecli/updatecli/pull/1245 

> I am planning to enriched PR content by using information changed by target, for that I need to update the target interface and I am planning to open a different pullrequest for that purpose only.

I would like to refactoring the target function to return the old and new value, so I could reuse that information in a pullrequest body such as 

## Example

<Actions>
    <action id="5ba2320a64327cb119aa710f75b537fb0095d1bb96839e46d8ddd2a9297d04ae">
        <h3>Bump Helm chart dependency &#34;dex&#34; for Helm chart &#34;epinio&#34;</h3>
        <details id="9d0fbf9349f646f1435072f2b0212084752ef4601bd6b012fbbe61b6c5e03930">
            <summary>Bump Helm chart dependency &#34;dex&#34; for Helm chart &#34;epinio&#34;</summary>
            changed from `0.13.0` to `0.14.0`
            <details>
                <summary>0.14.0</summary>
                <pre>This a changelog for version 0.14.0</pre>
            </details>
        </details>
    </action>
</actions>


A target changelog

**Comment by dduportal** [comment]
> That's an interesting view that I didn't considered, usually I see project fetching one information and then transforming for different target such as Dockerfile/Yaml/File, readme.md, etc. The first piece of information I am interested is identifying the target and the the information change. That being said in the current state we have changelog duplication

It's interesting to see all the different approaches ❤️ 

For me, the change is the "source" with simple PRs (most of my use cases). Target is an implementation detail: if I want to check the result of targets, then it is a code review of the PR.

But before that, knowing what "dependency" has been updated, with each version is a first step.
The goal is to evaluate quickly, before even checking the changelog, the expected amount of work to put on this review (otherwise I would have not used PR but direct commits).

Then, being able to access the changelog of the dependency is the 2nd most prior task, to deep dive.

Finally, the code review, associated with the checks, is the last mile: it's about "what did the target changed" and "are the checks OK with this change if testable".
