### ISSUE TITLE
When using `git` scm with `push=false` only the last target is left committed 

### ISSUE THREAD

**Issue by mcwarman** [updatecli/updatecli#1133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using multiple targets the changes get lost as the clone is reset to `.spec.branch` every time, when `--push=false` is set.

### Expected Behavior

All pipeline changes should be present.

#### Showing `git` not working

1. Apply the following patch:

```diff
diff --git a/e2e/updatecli.d/success.d/json.yaml b/e2e/updatecli.d/success.d/json.yaml
index b784b97..a00af52 100644
--- a/e2e/updatecli.d/success.d/json.yaml
+++ b/e2e/updatecli.d/success.d/json.yaml
@@ -1,5 +1,12 @@
 name: Basic Json Example
 
+scms:
+  default:
+    kind: git
+    spec:
+      url: https://github.com/updatecli/updatecli.git
+      branch: main
+
 sources:
   local:
     name: Get value from json
@@ -56,6 +63,7 @@ targets:
     name: Test value from json
     kind: json
     sourceid: local
+    scmid: default
     spec:
       file: pkg/plugins/resources/json/testdata/data.json
       key: firstName
@@ -65,9 +73,9 @@ targets:
     name: Test value from json
     kind: json
     sourceid: local
+    scmid: default
     spec:
       files:
-        - pkg/plugins/resources/json/testdata/data.json
         - pkg/plugins/resources/json/testdata/data.2.json
       key: firstName
       value: John

```

2. Execute test

```shell
updatecli apply --config ./e2e/updatecli.d/success.d/json.yaml --push=false
```

3. Check results:

```output
git log --oneline -n 3
c48ce4d0 (HEAD -> main) chore: Update key "firstName" from file "pkg/plugins/resources/json/t...
9765d1db (origin/main) fix: jenkins plugin comment
58c43036 Add `spec.files` for Condition and Target of `kind` `yaml` (#650)
```

### Environment

```markdown
- OS: Ubuntu-20.04 (WSL)
- updatecli: v0.43.0
```

**Comment by olblak** [comment]
Very early in the lifecycle of Updatecli we needed both workflow

1. Being able to commit directly to a head branch 
2. Being able to commit to a working branch

Back then, we decided to use the git scm type for the case one and github for the case two.
That decision didn't age very well.

Both @dduportal and I want to solve this but we took two different approaches 
Mine was to add a new boolean `disableworkingbranch` to all scm
-> https://github.com/updatecli/updatecli/issues/465

At the same time @dduportal started working on https://github.com/updatecli/updatecli/issues/465

With FOSDEM happening this weekend, we'll have the opportunity to talk about to see how we can finish

One rule we try to follow as much as possible is never introducing breaking changes.

**Comment by olblak** [comment]
> With the above decisions in mind, I think there's potentially still a bug with "Being able to commit to a working branch" with multiple targets as changes for the first commit don't get retained.

Definitely there is a bug here. Because Updatecli should commit and push changes after each target

**Comment by olblak** [comment]
Regarding Gitlab integration, I opened https://github.com/updatecli/updatecli/issues/738 to track the effort so feel free to add a +1

It's a bit of work but not really difficult as I leverage the [go-scm](github.com/drone/go-scm/scm) library like I did for [gitea](https://github.com/updatecli/updatecli/pull/744)

**Comment by mcwarman** [comment]
The branch is reset here: https://github.com/updatecli/updatecli/blob/main/pkg/plugins/utils/gitgeneric/main.go#L266-L269 on each target checkout, in the changes are not pushed, then this will reset back to origin.

**Comment by olblak** [comment]
Thanks for  pointing this out.

I am wondering if we should disable this behavior by default, and only enabled if the flag such as `--reset=true` is specified. Or just remove it.

I don't think exposing this parameter via the manifest would make sense

@dduportal has been looking at the scm refactoring so he may have some opinion here

**Comment by mcwarman** [comment]
The parameter makes sense, but I was having a think on this, and context probably changes the need, for a `source` and `condition` the reset is useful (and possibly a must). On `target` it causes the issue.

**Comment by olblak** [comment]
> The parameter makes sense, but I was having a think on this, and context probably changes the need, for a source and condition the reset is useful (and possibly a must). On target it causes the issue.

It's a very good point that it's useful for the shell resource, and in fact it would even solve some of the problem that I am facing with shell target executed in DRY_RUN

**Comment by olblak** [comment]
I have been thinking about this issue over the night. 
I am leaning toward:

* enabling/disabling the git reset from the git checkout operation via a scm spec parameter, we want to disable for the local scm by default and enable it by default at the beginning of an Updatecli run
* After each source/condition/target execute this git  reset operation but only in dry-run mode using `updatecli diff`. This is an additionnal safeguard and usefull for the shell resource
