### ISSUE TITLE
indentation mixup 

### ISSUE THREAD

**Issue by smerle33** [updatecli/updatecli#1198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

since a few days, the PR proposed by updatecli are screwing the indentation as for example : 

https://github.com/jenkins-infra/kubernetes-management/pull/3635/commits/c2f7ced6e296266bbf87ed00891a5851e7667242

### Expected Behavior

not to change the indentation

### Environment

```markdown
- updatecli: 0.44.4
```

**Comment by lemeurherve** [comment]
As discussed on the chat, the issue lies in https://github.com/updatecli/updatecli/compare/v0.43.0...v0.44.0

**Comment by lemeurherve** [comment]
More demonstrative PR showing the issue: https://github.com/jenkins-infra/helm-charts/pull/438/files

**Comment by olblak** [comment]
Indeed I also noticed this behavior change.
The "2" yaml indentation is not respected anymore
