### ISSUE TITLE
Feature Request: PR description a bit too verbose

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#1308]
### Is your feature request related to a problem?

Recent changes in the PR description are a bit too verbose

<img width="998" alt="image" src="https://user-images.githubusercontent.com/2871786/234968872-69ab672b-c1c4-4f84-b2c1-90cc00507d9d.png">

### Solution you'd like

I like the project and I think it's important to provide visibility but I wonder whether the information unrelated to the changes but the healthy of the project could be a bit less verbose

### Alternatives you've considered

https://github.com/updatecli/updatecli/blob/27aeab45b52538c44edb9d3730f316a1e0ce7c75/pkg/plugins/utils/action/main.go#L32-L40 could be in a collapse section

Though It might hide information that can benefit the updatecli ecosystem so people can engage easily by having those details in the PR itself. 

### Anything else?

We also use `mergify` and it uses `Mergify commands and options` to show all the details, see https://github.com/elastic/apm-server/pull/10686

I don't know whether that could be something sensible or maybe it hides things a bit too much.

Thanks for this project!

**Comment by olblak** [comment]
Thanks @v1v for the feedback, you explain very well the pro and cons of not hiding credits by default. 
When I redesigned the pullrequest body, I hesitate rather I wanted to hide or display by default the footer.

My initial attempt was to collapse so something like 




<Actions>
    <action id="7d76706e031243eca778bd19709353a00464cd0246087a166eb5392f82ceed37">
        <h3>Update Golang module github.com/moby/buildkit</h3>
        <details id="d7827c8bb6122dfe05d0ff2225a437df8edd401a3006682b03c4122a7b765303">
            <summary>Run Go mod tidy</summary>
        </details>
        <details id="f955470ff277fba9d568ffcd5349ed499039270904bee2182ec73b92444c30b7">
            <summary>Update github.com/moby/buildkit Golang module version</summary>
            <details>
                <summary>v0.11.6</summary>
                <pre>Changelog retrieved from:&#xA;&#x9;https://github.com/moby/buildkit/releases/tag/v0.11.6&#xA;https://hub.docker.com/r/moby/buildkit&#xD;&#xA;&#xD;&#xA;Notable changes:&#xD;&#xA;- Revert previous signal handling fix to make sure no process leaks happen. The signaling issue will be fixed in the next feature release. https://github.com/moby/buildkit/pull/3757&#xD;&#xA;- Update runc to v1.1.5 for security https://github.com/moby/buildkit/pull/3763&#xD;&#xA;- Update containerd to v1.6.20 . Brings in fix for not writing local user/group names in differ. #3736&#xD;&#xA;- Fix possible &#34;duplicate output 0&#34; error on parallel builds #3774&#xD;&#xA;- Fix token management for servers that don&#39;t return proper `IssuedAt` value #3779&#xD;&#xA;- Fix SBOM and provenance processing for certain nil-result cases #3805</pre>
            </details>
        </details>
    </action>
    <action id="83478edbc2b83c2dbd6fc2b031252d3ea99ebb6896c70e99d0c19ca0db6b7cda">
        <h3>Update Golang module github.com/google/go-containerregistry</h3>
        <details id="d7827c8bb6122dfe05d0ff2225a437df8edd401a3006682b03c4122a7b765303">
            <summary>Run Go mod tidy</summary>
        </details>
        <details id="f955470ff277fba9d568ffcd5349ed499039270904bee2182ec73b92444c30b7">
            <summary>Update github.com/google/go-containerregistry Golang module version</summary>
            <details>
                <summary>v0.14.0</summary>
                <pre>Changelog retrieved from:&#xA;&#x9;https://github.com/google/go-containerregistry/releases/tag/v0.14.0&#xA;## Changelog&#xA;* 9306ebad Allow crane edit to generate non-image artifacts (#1545)&#xA;* de35f0f7 Allow setting Content-Type in crane edit manifest (#1551)&#xA;* 4b081f80 Avoid v1.Manifest in crane edit config (#1583)&#xA;* 1cfe1fc2 Bump aws-actions/configure-aws-credentials from 1.7.0 to 2.0.0 (#1593)&#xA;* da1008fb Bump golangci/golangci-lint-action from 3.3.1 to 3.4.0 (#1548)&#xA;* 86be45fb Bump goreleaser/goreleaser-action from 4.1.0 to 4.1.1 (#1547)&#xA;* 62f183e5 Bump goreleaser/goreleaser-action from 4.1.1 to 4.2.0 (#1556)&#xA;* 1b8dc2ba Bump slsa-framework/slsa-github-generator from 1.2.2 to 1.5.0 (#1580)&#xA;* 11843ba2 Enforce proper sha256 usage (#1544)&#xA;* 2ceebaaf Implement crane index subcommand (#1561)&#xA;* 9f42e028 Set mediaType for empty.ImageIndex in RawManifest (#1562)&#xA;* 759b19f7 Support artifactType, for images whose config.mediaType is not a config (#1541)&#xA;* b3c23b4c Support for OCI 1.1+ referrers via API (#1546)&#xA;* 061ee6bf Support for OCI 1.1+ referrers via fallback tag (#1543)&#xA;* 67703048 Update descriptor &#34;data&#34; field (when valid) during &#34;crane edit config&#34; (#1584)&#xA;* 76bac933 Update release.yml (#1540)&#xA;* eb7d746c authn: also read mount secrets (#1560)&#xA;* e94d4089 bump deps using ./hack/bump-deps.sh (#1592)&#xA;* 4e95ae2b crane: add --flatten for index append (#1566)&#xA;* ff810c18 crane: add serve subcommand (#1586)&#xA;* 8ea5e0e8 crane: support --omit-digest-tags in crane ls (#1528)&#xA;* 824efc77 fix(mutate): also set timestamps only present in some formats (#1550)&#xA;* e04520bc fix: Fix the crane release url and add more steps (#1532)&#xA;* d8722327 hash: use generic instantiation (#1538)&#xA;* 57f010d2 replace manual slsa-verifier installation with action (#1585)&#xA;* 9cd098e3 skip tls verification if default transport is used with insecure option (#1559)&#xA;* 36249683 tarball: pass imageToTags (#1563)&#xA;&#xA;### Container Images&#xA;&#xA;https://gcr.io/go-containerregistry/crane:v0.14.0&#xA;https://gcr.io/go-containerregistry/gcrane:v0.14.0&#xA;&#xA;For example:&#xA;```&#xA;docker pull gcr.io/go-containerregistry/crane:v0.14.0&#xA;docker pull gcr.io/go-containerregistry/gcrane:v0.14.0&#xA;```&#xA;&#xA;</pre>
            </details>
        </details>
    </action>
    <action id="84fc35c4a3de68502ad1ebff49233d8bd4adb15be6c2bb9a3c39dff0029d038c">
        <h3>Update Golang module golang.org/x/mod</h3>
        <details id="d7827c8bb6122dfe05d0ff2225a437df8edd401a3006682b03c4122a7b765303">
            <summary>Run Go mod tidy</summary>
        </details>
        <details id="f955470ff277fba9d568ffcd5349ed499039270904bee2182ec73b92444c30b7">
            <summary>Update golang.org/x/mod Golang module version</summary>
        </details>
    </action>
    <action id="c143ad06840fdf89128414da9fe62de3b1f2aa38b32de7403d2fb36797435c15">
        <h3>Update Golang module github.com/aws/aws-sdk-go</h3>
        <details id="d7827c8bb6122dfe05d0ff2225a437df8edd401a3006682b03c4122a7b765303">
            <summary>Run Go mod tidy</summary>
        </details>
        <details id="f955470ff277fba9d568ffcd5349ed499039270904bee2182ec73b92444c30b7">
            <summary>Update github.com/aws/aws-sdk-go Golang module version</summary>
            <details>
                <summary>v1.44.247</summary>
                <pre>Changelog retrieved from:&#xA;&#x9;https://github.com/aws/aws-sdk-go/releases/tag/v1.44.247&#xA;Release v1.44.247 (2023-04-20)&#xA;===&#xA;&#xA;### Service Client Updates&#xA;* `service/chime`: Updates service API and documentation&#xA;  * Adds support for Hindi and Thai languages and additional Amazon Transcribe parameters to the StartMeetingTranscription API.&#xA;* `service/chime-sdk-media-pipelines`: Updates service API and documentation&#xA;* `service/chime-sdk-meetings`: Updates service API and documentation&#xA;* `service/gamelift`: Updates service API and documentation&#xA;  * Amazon GameLift supports creating Builds for Windows 2016 operating system.&#xA;* `service/guardduty`: Updates service API and documentation&#xA;  * This release adds support for the new Lambda Protection feature.&#xA;* `service/iot`: Updates service API and paginators&#xA;  * Support additional OTA states in GetOTAUpdate API&#xA;* `service/sagemaker`: Updates service API and documentation&#xA;  * Amazon SageMaker Canvas adds ModelRegisterSettings support for CanvasAppSettings.&#xA;* `service/snowball`: Updates service API and documentation&#xA;  * Adds support for Amazon S3 compatible storage. AWS Snow Family customers can now use Amazon S3 compatible storage on Snowball Edge devices. Also adds support for V3_5S. This is a refreshed AWS Snowball Edge Storage Optimized device type with 210TB SSD (customer usable).&#xA;* `service/wafv2`: Updates service API and documentation&#xA;&#xA;</pre>
            </details>
            <details>
                <summary>v1.44.248</summary>
                <pre>Changelog retrieved from:&#xA;&#x9;https://github.com/aws/aws-sdk-go/releases/tag/v1.44.248&#xA;Release v1.44.248 (2023-04-21)&#xA;===&#xA;&#xA;### Service Client Updates&#xA;* `service/connect`: Updates service API and documentation&#xA;* `service/ecs`: Updates service documentation&#xA;  * Documentation update to address various Amazon ECS tickets.&#xA;* `service/fms`: Updates service API, documentation, and paginators&#xA;&#xA;</pre>
            </details>
            <details>
                <summary>v1.44.249</summary>
                <pre>Changelog retrieved from:&#xA;&#x9;https://github.com/aws/aws-sdk-go/releases/tag/v1.44.249&#xA;Release v1.44.249 (2023-04-24)&#xA;===&#xA;&#xA;### Service Client Updates&#xA;* `service/appflow`: Updates service API&#xA;* `service/ec2`: Updates service API and documentation&#xA;  * API changes to AWS Verified Access related to identity providers&#39; information.&#xA;* `service/mediaconvert`: Updates service API and documentation&#xA;  * This release introduces a noise reduction pre-filter, linear interpolation deinterlace mode, video pass-through, updated default job settings, and expanded LC-AAC Stereo audio bitrate ranges.&#xA;* `service/rekognition`: Updates service API and documentation&#xA;  * Added new status result to Liveness session status.&#xA;&#xA;</pre>
            </details>
            <details>
                <summary>v1.44.250</summary>
                <pre>Changelog retrieved from:&#xA;&#x9;https://github.com/aws/aws-sdk-go/releases/tag/v1.44.250&#xA;Release v1.44.250 (2023-04-25)&#xA;===&#xA;&#xA;### Service Client Updates&#xA;* `service/chime-sdk-messaging`: Updates service API and documentation&#xA;* `service/connect`: Updates service API, documentation, and paginators&#xA;* `service/datasync`: Updates service API, documentation, and paginators&#xA;* `service/ds`: Updates service API and documentation&#xA;  * New field added in AWS Managed Microsoft AD DescribeSettings response and regex pattern update for UpdateSettings value.  Added length validation to RemoteDomainName.&#xA;* `service/pinpoint`: Updates service API, documentation, and examples&#xA;  * Adds support for journey runs and querying journey execution metrics based on journey runs. Adds execution metrics to campaign activities. Updates docs for Advanced Quiet Time.&#xA;&#xA;</pre>
            </details>
            <details>
                <summary>v1.44.251</summary>
                <pre>Changelog retrieved from:&#xA;&#x9;https://github.com/aws/aws-sdk-go/releases/tag/v1.44.251&#xA;Release v1.44.251 (2023-04-26)&#xA;===&#xA;&#xA;### Service Client Updates&#xA;* `service/osis`: Updates service API, documentation, paginators, and examples&#xA;&#xA;</pre>
            </details>
            <details>
                <summary>v1.44.252</summary>
                <pre>Changelog retrieved from:&#xA;&#x9;https://github.com/aws/aws-sdk-go/releases/tag/v1.44.252&#xA;Release v1.44.252 (2023-04-27)&#xA;===&#xA;&#xA;### Service Client Updates&#xA;* `service/ec2`: Updates service API and documentation&#xA;  * This release adds support for AMD SEV-SNP on EC2 instances.&#xA;* `service/emr-containers`: Updates service API and documentation&#xA;* `service/guardduty`: Updates service API and documentation&#xA;  * Added API support to initiate on-demand malware scan on specific resources.&#xA;* `service/iotdeviceadvisor`: Updates service API and documentation&#xA;* `service/kafka`: Updates service API, documentation, and paginators&#xA;* `service/lambda`: Updates service API&#xA;  * Add Java 17 (java17) support to AWS Lambda&#xA;* `service/marketplace-catalog`: Updates service paginators&#xA;* `service/osis`: Updates service documentation&#xA;* `service/qldb`: Updates service documentation&#xA;* `service/sagemaker`: Updates service API and documentation&#xA;  * Added ml.p4d.24xlarge and ml.p4de.24xlarge as supported instances for SageMaker Studio&#xA;* `service/xray`: Adds new service&#xA;  * Updated X-Ray documentation with Resource Policy API descriptions.&#xA;&#xA;</pre>
            </details>
        </details>
    </action>
</Actions>

---

<details><summary>Updatecli options</summary>

Action triggered automatically by [Updatecli](https://www.updatecli.io).

<p>Most of Updatecli configuration is done via Updatecli manifest.</p>
<ul>
<li>If you close this pullrequest, Updatecli will automatically reopen it, the next time it runs.</li>
<li>If you close this pullrequest, and delete the base branch, Updatecli will automatically recreate it, erasing all previous commits made.</li>
</ul>

Feel free to report any issues at [github.com/updatecli/updatecli](https://github.com/updatecli/updatecli/issues/).
If you find this tool useful, do not hesitate to star our GitHub repository [github.com/updatecli/updatecli](https://github.com/updatecli/updatecli/stargazers) as a sign of appreciation.
Or tell us directly on our [chat](https://matrix.to/#/#Updatecli_community:gitter.im)

<img src="https://www.updatecli.io/images/updatecli.png" alt="Updatecli logo" width="200" height="200">

</details>

**Comment by olblak** [comment]
<Actions>
    <action id="7d76706e031243eca778bd19709353a00464cd0246087a166eb5392f82ceed37">
        <h3>Update Golang module github.com/moby/buildkit</h3>
        <details id="d7827c8bb6122dfe05d0ff2225a437df8edd401a3006682b03c4122a7b765303">
            <summary>Run Go mod tidy</summary>
        </details>
        <details id="f955470ff277fba9d568ffcd5349ed499039270904bee2182ec73b92444c30b7">
            <summary>Update github.com/moby/buildkit Golang module version</summary>
            <details>
                <summary>v0.11.6</summary>
                <pre>Changelog retrieved from:&#xA;&#x9;https://github.com/moby/buildkit/releases/tag/v0.11.6&#xA;https://hub.docker.com/r/moby/buildkit&#xD;&#xA;&#xD;&#xA;Notable changes:&#xD;&#xA;- Revert previous signal handling fix to make sure no process leaks happen. The signaling issue will be fixed in the next feature release. https://github.com/moby/buildkit/pull/3757&#xD;&#xA;- Update runc to v1.1.5 for security https://github.com/moby/buildkit/pull/3763&#xD;&#xA;- Update containerd to v1.6.20 . Brings in fix for not writing local user/group names in differ. #3736&#xD;&#xA;- Fix possible &#34;duplicate output 0&#34; error on parallel builds #3774&#xD;&#xA;- Fix token management for servers that don&#39;t return proper `IssuedAt` value #3779&#xD;&#xA;- Fix SBOM and provenance processing for certain nil-result cases #3805</pre>
            </details>
        </details>
    </action>
</Actions>


---

<table>
  <tr style="text-align: center; vertical-align: center;">
    <td width="80" height="80"  >
<img src="https://www.updatecli.io/images/updatecli.png" alt="Updatecli logo" width="50" height="50">
    </td>
    <td>
      <p>
        Action triggered automatically by <a href="https://www.updatecli.io">Updatecli</a></br>
        Feel free to report any issues at <a href="https://github.com/updatecli/updatecli/issues">github.com/updatecli/updatecli</a>. If you find this tool useful, do not hesitate to star our GitHub repository <a href="https://github.com/updatecli/updatecli/stargazers">github.com/updatecli/updatecli</a> as a sign of appreciation. Or to tell us directly on our <a href="https://matrix.to/#/#Updatecli_community:gitter.im">chat</a>
      </p>
    </td>
  </tr>
</table>

<details><summary>Updatecli options</summary>
<p>Most of Updatecli configuration is done via Updatecli manifest.</p>
<ul>
<li>If you close this pullrequest, Updatecli will automatically reopen it, the next time it runs.</li>
<li>If you close this pullrequest, and delete the base branch, Updatecli will automatically recreate it, erasing all previous commits made.</li>
</ul>
</details>

**Comment by olblak** [comment]
@v1v What would you think of the previous example?

**Comment by lemeurherve** [comment]
---
<table>
  <tr style="text-align: center; vertical-align: center;">
    <td width="80" height="80"  >
<img src="https://www.updatecli.io/images/updatecli.png" alt="Updatecli logo" width="50" height="50">
    </td>
    <td>
      <p>
        Action triggered automatically by <a href="https://www.updatecli.io">Updatecli</a>. Feel free to report any issues at <a href="https://github.com/updatecli/updatecli/issues">github.com/updatecli/updatecli</a>. If you find this tool useful, do not hesitate to star <a href="https://github.com/updatecli/updatecli/stargazers">our GitHub repository</a> as a sign of appreciation, or to tell us directly on our <a href="https://matrix.to/#/#Updatecli_community:gitter.im">chat</a>!
<details><summary>Updatecli options</summary>
<p>Most of Updatecli configuration is done via Updatecli manifest.</p>
<ul>
<li>If you close this pullrequest, Updatecli will automatically reopen it, the next time it runs.</li>
<li>If you close this pullrequest, and delete the base branch, Updatecli will automatically recreate it, erasing all previous commits made.</li>
</ul>
</details>
      </p>
    </td>
  </tr>
</table>

```
---
<table>
  <tr style="text-align: center; vertical-align: center;">
    <td width="80" height="80"  >
<img src="https://www.updatecli.io/images/updatecli.png" alt="Updatecli logo" width="50" height="50">
    </td>
    <td>
      <p>
        Action triggered automatically by <a href="https://www.updatecli.io">Updatecli</a>. Feel free to report any issues at <a href="https://github.com/updatecli/updatecli/issues">github.com/updatecli/updatecli</a>. If you find this tool useful, do not hesitate to star <a href="https://github.com/updatecli/updatecli/stargazers">our GitHub repository</a> as a sign of appreciation, or to tell us directly on our <a href="https://matrix.to/#/#Updatecli_community:gitter.im">chat</a>!
<details><summary>Updatecli options</summary>
<p>Most of Updatecli configuration is done via Updatecli manifest.</p>
<ul>
<li>If you close this pullrequest, Updatecli will automatically reopen it, the next time it runs.</li>
<li>If you close this pullrequest, and delete the base branch, Updatecli will automatically recreate it, erasing all previous commits made.</li>
</ul>
</details>
      </p>
    </td>
  </tr>
</table>
```

A bit shorter, not enough yet to my taste...

**Comment by olblak** [comment]
I know realise the logo do not render on mobile anyway so I am going to remove the collapse by default

**Comment by lemeurherve** [comment]
As discussed on the chat the logo is fine on mobile.

---
<table>
  <tr>
    <td width="80">
<img src="https://www.updatecli.io/images/updatecli.png" alt="Updatecli logo" width="50" height="50">
    </td>
    <td>
      <p>
        Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
<details><summary>Options:</summary>
<br />
<p>Most of Updatecli configuration is done via Updatecli manifest(s).</p>
<ul>
<li>If you close this pull request, Updatecli will automatically reopen it, the next time it runs.</li>
<li>If you close this pull request and delete the base branch, Updatecli will automatically recreate it, erasing all previous commits made.</li>
</ul>

Feel free to report any issues at <a href="[https://github.com/updatecli/updatecli/issues](https://github.com/updatecli/updatecli/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)">updatecli/updatecli</a>. If you find this tool useful, do not hesitate to star <a href="https://github.com/updatecli/updatecli/stargazers">our GitHub repository</a> as a sign of appreciation, or to tell us directly on our <a href="https://matrix.to/#/#Updatecli_community:gitter.im">chat</a>!
</details>
      </p>
    </td>
  </tr>
</table>


---
New suggestion, WDYT?

I've changed "Action triggered" by "Created" as it can come from Jenkins or any other CI tools, not necessarily GitHub Action.

I also avoided "Pull request created <...>" as Updatecli can be used on GitLab.

<details>
<summary>corresponding markdown:</summary>

```
---
<table>
  <tr>
    <td width="80">
<img src="https://www.updatecli.io/images/updatecli.png" alt="Updatecli logo" width="50" height="50">
    </td>
    <td>
      <p>
        Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
<details><summary>Options</summary>
<br />
<p>Most of Updatecli configuration is done via Updatecli manifest(s).</p>
<ul>
<li>If you close this pull request, Updatecli will automatically reopen it, the next time it runs.</li>
<li>If you close this pull request and delete the base branch, Updatecli will automatically recreate it, erasing all previous commits made.</li>
</ul>

Feel free to report any issues at <a href="[https://github.com/updatecli/updatecli/issues](https://github.com/updatecli/updatecli/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)">updatecli/updatecli</a>. If you find this tool useful, do not hesitate to star <a href="https://github.com/updatecli/updatecli/stargazers">our GitHub repository</a> as a sign of appreciation, or to tell us directly on our <a href="https://matrix.to/#/#Updatecli_community:gitter.im">chat</a>!
</details>
      </p>
    </td>
  </tr>
</table>
```

</details>

**Comment by olblak** [comment]
I like it very much, I'll create a PR tomorrow when I have access to a laptop
