### ISSUE TITLE
Feature Request: multiple values files can be specified

### ISSUE THREAD

**Issue by gionn** [updatecli/updatecli#1403]
### Is your feature request related to a problem?

Like with the helm cli, it should be possible to specify multiple `--values` options so values file can be split in smaller chunks, which would also increase the reusability across different updatecli pipelines.

### Solution you'd like

when multiple `--values` files are provided, they got merged in a single structure, the latter has precedence.

### Alternatives you've considered

yaml files can be pre-processed with yq before using updatecli, and may still be necessary if some custom merging behavior is desired (e.g. array merging policy)

**Comment by olblak** [comment]
I had a quick look at the code, and as far as I could see it should already be working (but it doesn't) so it sounds more a bug to me

**Comment by dduportal** [comment]
@olblak I remember we had weird behaviors when deep-merging, that's why it was not enabled
