### ISSUE TITLE
On Windows --values is broken

### ISSUE THREAD

**Issue by stevehipwell** [updatecli/updatecli#1415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

However I specify `--values` on a Windows machine I get the following error.

> ERROR: failed loading pipeline(s)
        * "updatecli\\updatecli.d\\test.yaml" - stat updatecli\values.yaml: invalid argument

### Expected Behavior

I'd expect the `--values` argument to work with relative or absolute paths.

### Steps To Reproduce

1. In Windows
2. Run `updatecli diff --config <config_dir> --values <values_path>`

### Environment

```markdown
- OS: Windows 11
- updatecli: v0.54.0
```

**Comment by olblak** [comment]
I did some testing, and this pull request https://github.com/updatecli/updatecli/pull/1447
solves the current issue.

It will be available in the next release 0.56.0
