### ISSUE TITLE
Misleading commit message for the file plugin

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Commits created by the file plugin are quite misleading 

```
[chore: Updated to content "" in file "README.md"](https://github.com/rancher/fleet/pull/1720/commits/d3ce14d5394630d3e22ab2f8928a247541fa8fa7)
```

### Expected Behavior

Ideally I would like a commit message explaining what changed.
The problem is that it could be challenging to identify what changed.
On top of this, sometimes a lot of things can be changed by the file plugin...

Instead of:
* `chore: Updated to content "" in file "README.md` 

We can have one of the following message:
* ```chore: Updated to content "v.7.0.1" in file "README.md```
* ```chore: Updated to content `ghcr.io/...` in file "README.md"
 

### Steps To Reproduce

https://github.com/rancher/fleet/blob/master/updatecli/updatecli.d/installation.yaml

### Environment

```markdown
- OS: OpenSuse TumbleWeed
- updatecli: 0.57.0
```

**Comment by dduportal** [comment]
For the record, it used to show the difference but it seems broken

**Comment by olblak** [comment]
I moved the diff in the debug level because it printed a lot of information but I am considering moving it back in the info

**Comment by olblak** [comment]
Would you be ok with :

<details><summary>Case with multiple file</summary>

```
commit 72b8cb420f65d9bb96d3c8a57249e0e7680cc8a8 (HEAD -> updatecli_fc0be06d9602411bcf37d17fe8e7df3fd48bf7d0f7811efd3e3ea7e394d10ef6)
Author: epinio-bot <bot@epinio.io>
Date:   Fri Aug 18 12:51:39 2023 +0200

    chore: 2 files updated with "https://github.com/cert-manager/cert-man...
    
    ... ager/releases/download/v0.16.1/":
            *docs/installation/other_inst_scenarios/install_epinio_on_rancher_desktop.md
            *docs/tutorials/single-dev-workflow.md
    
    Made with ❤️️ by updatecli
****
```

<details>

**Comment by olblak** [comment]
The problem is the description is used for the commit title by default and the file plugin may change a lot of files or the content change can be huge

**Comment by olblak** [comment]
Thanks @thardeck for the feedback, as you made a very good point here.
It doesn't add any value to have detailed description as we can already guess from the git diff.

What annoys me with just using the file name is that can be hard to differenciate between different kind of change targeting the same file.

I am starting to wonder if the problem is not elswhere.
Instead of using the description for the commit title, I could reuse the target name

In  this case, it would be something like 

```
 chore: Update Epinio installation URL
```

**Comment by olblak** [comment]
Thank you both for your suggestion.

I'll open a pullrequest with a few improvement for the "file" plugin to diff by default

And a second pullrequest to use target name for commit title by default, if no target title specified the we use the current change description

**Comment by hervelemeur** [comment]
Why not use the PR title aka the action title as commit message ?

**Comment by olblak** [comment]
> Why not use the PR title aka the action title as commit message ?

By default the PR title is based on the first target name, the suggestion is to align on that

**Comment by olblak** [comment]
I just did some testing and I prefer the approach of reusing the target title 

<details>

```
commit 03b1b44a38580d6f5fb8fb531f7b6809ea3f1149 (HEAD -> updatecli_fc0be06d9602411bcf37d17fe8e7df3fd48bf7d0f7811efd3e3ea7e394d10ef6)
Author: epinio-bot <bot@epinio.io>
Date:   Fri Aug 18 15:13:40 2023 +0200

    chore: Update Epinio Installation URL
    
    Made with ❤️️ by updatecli

diff --git a/docs/installation/other_inst_scenarios/install_epinio_on_rancher_desktop.md b/docs/installation/other_inst_scenarios/install_epinio_on_rancher_desktop.md
index 895d18b09..84e327c26 100644
--- a/docs/installation/other_inst_scenarios/install_epinio_on_rancher_desktop.md
+++ b/docs/installation/other_inst_scenarios/install_epinio_on_rancher_desktop.md
@@ -47,7 +47,7 @@ The Epinio installation is similar on Linux, MacOS and Windows:
 

 
-kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.3/cert-manager.yaml
+kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v0.16.1/cert-manager.yaml
 
 # Wait for cert-manager to stabilize
 
diff --git a/docs/tutorials/single-dev-workflow.md b/docs/tutorials/single-dev-workflow.md
index 79622e1ce..207463288 100644
--- a/docs/tutorials/single-dev-workflow.md
+++ b/docs/tutorials/single-dev-workflow.md
@@ -69,7 +69,7 @@ Once you have your local Kubernetes cluster installed and running, you can

```

</details>

**Comment by mcwarman** [comment]
Bit late to this, but it does closely lines up with what I've rested on as my "default" config.

https://github.com/mcwarman/helm-charts/blob/main/updatecli.d/postgres-chart.yaml#L30
https://github.com/mcwarman/helm-charts/blob/main/updatecli.d/postgres-chart.yaml#L53
