### ISSUE TITLE
Improve distribution of updateCli

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#154]
**Is your feature request related to a problem? Please describe.**

* I would like to verify the checksum of the `updateCli` binary I'm downloading
* I would like to be able to use `updateCli` as a Docker image sometimes (instead of a binary)
* As a macOS user, I would like to be able to install and update `updateCli` with homebrew, the package manager

**Describe the solution you'd like**

The goreleaser tool (https://goreleaser.com/) could be a great help for solving all of this requests at once (and maybe more)

**Describe alternatives you've considered**

* Scripting the generation of checksum can be done quite easily
* It looks like there is already a Dockerfile at the repository's root: adding a piece of doc could be helpful

**Additional context**

N.A.

**Comment by olblak** [comment]
Almost everything as been implemented in https://github.com/updatecli/updatecli/releases/tag/v0.3.4
I am still missing the brew part but as I a non macOS user, I am not planning to spend more time on this
