### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#157]
**Is your feature request related to a problem? Please describe.**

As a newcomer, I've innitialy missed some conceptual points and add to ask a question... which answer was already in the doc.

**Describe the solution you'd like**

The documentation could be updated to make the newcomer's path a bit smoother:

- The Configuration section could be split in 2 sections: "Concepts" and "Configuration" (YAML + TPL)
- Update Intro (and all go further sections) to point to concepts
- Add a flow diagram to help visually understand (on both Intro and concept pages)

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by dduportal** [comment]
Closing as documentation is on another repo + need an overhall update so this issue is not relevant anymore.

**Comment by lemeurherve** [comment]
Shouldn't (a part at list of) the doc be more close to the code? And maybe extracted into the doc repo so there would be less drift between them?

**Comment by dduportal** [comment]
> Shouldn't (at least a part of) the doc be more close to the code? And maybe extracted into the doc repo so there would be less drift between them?

Yep: https://github.com/updatecli/website/issues/188#issuecomment-1014871599 :)
