### ISSUE TITLE
Feature Request: Support for pinning digests by image config

### ISSUE THREAD

**Issue by jawnsy** [updatecli/updatecli#1603]
### Is your feature request related to a problem?

When pinning Docker Digests, `updatecli` currently uses the architecture-specific digest. We can [specify the architecture to use](https://github.com/updatecli/updatecli/blob/76519529efe80a3fabc1f83a70f97cd163de189a/pkg/plugins/resources/dockerdigest/main.go#L13-L23), but we can only specify one at a time (e.g. `amd64`, the default, or `arm64`)

### Solution you'd like

I recently learned from the illustrious @jonjohnsonjr that [we can pin the image index instead of a specific image digest](https://github.com/chainguard-dev/edu/issues/941#issuecomment-1719736213). 🤯 

Support for pinning the image index digest would mean that we can reproducibly pin multiarch image versions, without restricting us to single-architecture clusters. This would mean that we're pinning to a digest (and get all the reproducibility benefits of pinning), but that we can also support multiarch images.

### Alternatives you've considered

Some viable workarounds are to pin to a specific architecture and use `nodeSelector` to make sure that the image runs on the correct node (for Kubernetes clusters), use taints/tolerations, or otherwise avoid using mixed-architecture clusters

**Comment by olblak** [comment]
This is great, I wasn't aware of it.
I guess we need to figure out how to retrieve that information
https://github.com/updatecli/updatecli/blob/c6150b3663dcd144da43f09ea351623f9a90b73b/pkg/plugins/resources/dockerdigest/source.go#L38

**Comment by jonjohnsonjr** [comment]
You can use remote.Head or remote.Get if you just want the digest.

**Comment by olblak** [comment]
Thanks everybody for the suggestion here, 
I just opened a pullrequest https://github.com/updatecli/updatecli/pull/1712

@jawnsy I made the assumption that if we don't specify an architecture then we retrieve the config digest.
I am wondering if this new behavior could be considered as a regression, I don't think so 🤷🏾
