### ISSUE TITLE
"dockerimage": unauthorized as of v0.60.0

### ISSUE THREAD

**Issue by CrystalMethod** [updatecli/updatecli#1613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting with v0.60.0 we see our manifests failing to update sources of kind "dockerimage". We have noticed the release notes as of version 0.60.0 regarding sources kind of "dockerimage". But we do not see any connection with this UNAUTHORIZED error message here.

### Steps To Reproduce

```
sources:
  latestVersion:
    name: Get latest version from image registry
    kind: dockerimage
    spec:
      image: <acr>.azurecr.io/<repo>
      versionfilter:
        kind: semver
        pattern: "~1.0.0-0"
```

Here ist the debug output using v0.60.0/v0.61.0:

```
SOURCES
=======

latestVersion
-------------
DEBUG: Searching tags for the image "<acr>.azurecr.io/<repo>"
DEBUG: 28 Docker image tag(s) found
Searching for version matching pattern "~1.0.0-0"
ERROR: ✗ GET https://<acr>.azurecr.io/oauth2/token?scope=repository%3A<repo>%3Apull&service=<acr>.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more i
nformation.
ERROR: {Get latest version from image registry ✗   { {  } }   DEBUG: Searching tags for the image "<acr>.azurecr.io/<repo>"
DEBUG: 28 Docker image tag(s) found
Searching for version matching pattern "~1.0.0-0"
ERROR: ✗ GET https://<acr>.azurecr.io/oauth2/token?scope=repository%3A<repo>%3Apull&service=<acr>.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more i
nformation.
} GET https://<acr>.azurecr.io/oauth2/token?scope=repository%3A<repo>%3Apull&service=<acr>.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more informat
ion.
Pipeline "Bump devops-toolbox version" failed
Skipping due to:
        sources stage:  "GET https://<acr>.azurecr.io/oauth2/token?scope=repository%3A<repo>%3Apull&service=<acr>.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authoriz
ation for more information."
```

The same manifest runs without errors up to version 0.59.0.

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- updatecli: v0.61.0
```

**Comment by olblak** [comment]
Thanks for reporting this issue.

I see that you still manage to retrieve some information from your remote registry but not everything.
Is it a public or private repository? 
Did you correctly run `docker login <acr>.azurecr.io` from the environment where you execute `updatecli` command?

I'll try to reproduce within the week

**Comment by olblak** [comment]
0.60.0 contains a fix that correctly retrieve arch information for docker image, maybe one of the request is missing authentication setting

**Comment by CrystalMethod** [comment]
Thanks for your reply. Its a private registry, and yes, I'm fully authenticated locally. As soon as I switch back to 0.59.0 and rerun the manifest, everything works as expected. Your assumption of the missing authentication for some new requests sound reasonable, because the debug output shows that "28 Docker image tag(s) found" - and I'm quite sure that you need to be authenticated for this request as well.

**Comment by olblak** [comment]
Thanks for the feedback, I managed to reproduced the problem with a private repository and indeed it was a minor fix.
The default authentication options weren't defined if the architecture wasn't defined.

**Comment by CrystalMethod** [comment]
v0.61.1 works as expected, many thanks for the quick fix
