### ISSUE TITLE
Feature Request: Infer the GitHub action that created the GitHub Pull Request

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#1717]
### Is your feature request related to a problem?

Track what GitHub workflow created the GitHub Pull Request automatically.

### Solution you'd like

Infer the GitHub workflow URL when using the target `github/pullrequest` automatically and likely with an option to opt-out:

```yaml
actions:
  default:
    kind: github/pullrequest
    spec:
      inferGithubWorkflow: false
```

Will then include in the description of the Pull Request the URL to the gitHub workflow that triggered the udpatecli config.

### Alternatives you've considered

I've been using an env variable in conjunction with the GitHub action env generation

See https://github.com/elastic/apm-pipeline-library/blob/9c712c2558ef07309c4ddf3cf02d20a1cb2b1b3a/updatecli/updatecli.d/bump-aliases.yml#L14 and https://github.com/elastic/apm-pipeline-library/blob/9c712c2558ef07309c4ddf3cf02d20a1cb2b1b3a/.github/workflows/bump-aliases.yml#L12-L13

But I'd like to get that for free.

### Anything else?

`GITHUB_REPOSITORY`, `GITHUB_RUN_ID` and `GITHUB_SERVER_URL` are some of the required env variables that are available as far as I see in https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

https://github.com/elastic/apm-pipeline-library/pull/2398

<img width="996" alt="image" src="https://github.com/updatecli/updatecli/assets/2871786/c691455d-447d-4aae-84d3-1f1e3d21582b">

**Comment by olblak** [comment]
Thanks for your suggestion, I like this idea very much and I don't think we need to specify a new parameter like `inferGitHubWorkflow`

All we have to do is to check if mentioned environment variable are set and update https://github.com/updatecli/updatecli/blob/b0a905731860c54bdd084919df4b67c1ca17cc01/pkg/core/reports/action.go#L16

I wasn't considering doing the same for Jenkins

**Comment by olblak** [comment]
Also I think it would be nice to also implement it for Jenkins

Globally I think it would  be safer to disable it by default as the risk is to accidentally leak URL to the CI environments.
This could be a setting at the action level

```
actions:
    default:
        kind: github/pullrequest
        pipelineeurl: true
```

**Comment by dduportal** [comment]
> Also I think it would be nice to also implement it for Jenkins
> 
> Globally I think it would be safer to disable it by default as the risk is to accidentally leak URL to the CI environments. This could be a setting at the action level
> 
> ```
> actions:
>     default:
>         kind: github/pullrequest
>         pipelineeurl: true
> ```

Good point, it looks like a method with a switch/case could take care of detecting the originating CI (GHA, or Jenkins, or gitlab, etc.) only based on environment variables could be really really useful \o/

**Comment by v1v** [comment]
> This could be a setting at the action level

I like this approach, and makes totally sense to disable it by default! 👍
