### ISSUE TITLE
Failure to load pipeline not reported when there are multiple configs

### ISSUE THREAD

**Issue by mcwarman** [updatecli/updatecli#1720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When multiple manifest are loaded if one fails to load pipeline its not reported as a failure.

```
./updatecli.d/pre-commit-megalinter.yaml
./updatecli.d/updatecli.yaml                    # misconfigured SCM
```

```shell
updatecli diff
```

Will report:

```
Loading Pipeline "updatecli.d/pre-commit-megalinter.yaml"
Loading Pipeline "updatecli.d/updatecli.yaml"
ERROR: failed loading pipeline(s)
        * "updatecli.d/updatecli.yaml" - scm id "default1" doesn't exist
....
Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     0
  * Skipped:    0
  * Succeeded:  1
  * Total:      1
```

```shell
❯ echo $?
0
```

### Expected Behavior

Failure should be reported, this is also important when updatecli is run in pipeline as failures will get ignored.

### Steps To Reproduce

1. Create project with multiple manifests
2. Update something to cause pipeline fail to load (`scmid`)

### Environment

```markdown
- OS: Ubuntu 20.04.6 LTS (WSL)
- updatecli: v0.64.1
```

### Anything else?

Failures that occur in targets etc. still appear to be reported correctly. Also if you run the pipeline with `--config` it errors as expected:

```shell
updatecli diff --config updatecli.d/updatecli.yaml
```

```
+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli.d/updatecli.yaml"
ERROR: failed loading pipeline(s)
        * "updatecli.d/updatecli.yaml" - scm id "default1" doesn't exist

0 pipeline(s) successfully loaded

SCM repository retrieved: 0


++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++

ERROR: ✗ no valid pipeline found
ERROR: command failed: no valid pipeline found
```

**Comment by mcwarman** [comment]
Thinking it through the question is :

Should it fail fast if anything fails to load?
Should we run the pipelines that were loaded successfully and report a failure of the other?

**Comment by olblak** [comment]
Good catch, I think it makes sense to add a report for each pipeline configuration that couldn't be loaded correctly.
This should be trivial to solve as I think this [function](https://github.com/updatecli/updatecli/blob/19e0b9356f0485ae53b3f1f87b8771c81e224082/pkg/core/engine/prepare.go#L23) could be modified to return the number of failed pipeline and then we can just append report result similarly to how we do for source/condition/target execution

> Should it fail fast if anything fails to load?

I don't think we should fail fast. The risk is to not executed unrelated pipeline

> Should it run the pipelines that were loaded successfully and report a failure of the other?

I think we should correctly notify that an Updatecli execution failed at some po
