### ISSUE TITLE
scm working branch diverged from target branch

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Updatecli is executed using the GitHub scm, it clones the git repository mentioned in the scm configuration into the directory `/tmp/updatecli/github/...` (assuming Linux machine), then it generates a "working branch" such as "updatecli_xxx" based on the branch configuration such "main".

At the end of the pipeline, and in a case of a change detected, Updatecli pushes that branch to remote location.

Starting from now, each future run of Updatecli will reuse that "working" branch without doing additional rebase/merge operation which means that base branch and the working branch now diverged. The longer we wait to merge a pullrequest and bigger is the risk to face issues...

For example all autodiscovery plugins, by design, always run before knowing "working branches".
So a situation that I encounter from time to time on the updatecli/updatecli is with the autodiscovery Golang plugin

1. Trigger updatecli a first time: autodiscovery generates one pipeline per Golang module and  open a pullrequest with all Golang patch update available
2. I merge a none related pullrequest with a new feature that introduces new Golang modules.
3. Trigger updatecli a second time: autodiscovery generates one pipeline per Golang module (including for those introduce in step 2)

Problem: The generated pipeline for the new golang module introduce in step 2 fails in step 3 because the generated branch in step 1 is outdated against the main branch

### Expected Behavior

Working branch should always be ahead of the target branch.
A solution could be either:

1. Automatically merge target branch into the working branch
2. Automatically rebase target branch and force push

~~Both approaches could easily be handled https://github.com/updatecli/updatecli/blob/657fd66e364c957e2961a177b44dade2862e5446/pkg/plugins/utils/gitgeneric/main.go#L322~~

but I am more concerned by edgecase that I don't see

### Steps To Reproduce

1. Trigger updatecli a first time: autodiscovery generates one pipeline per Golang module and  open a pullrequest with all Golang patch update available
2. I merge a none related pullrequest with a new feature that introduces new Golang modules.
3. Trigger updatecli a second time: autodiscovery generates one pipeline per Golang module (including for those introduce in step 2)

Problem: The generated pipeline for the new golang module introduce in step 2 fails in step 3 because the generated branch in step 1 is outdated against the main branch

### Environment

```markdown
- OS: linux
- updatecli: 0.65.0
```

**Comment by olblak** [comment]
I think I would be more in favor of merging automatically (no force push) and if a merge conflict happen, we can still fail the pipeline asking to delete the working branch

**Comment by mprzybylski** [comment]
I've run into this issue with some pipelines my colleagues and I are working on.  Rebase + force-push would work better for our use case.  Would it be possible to add a parameter to allow us to select our preferred behavior?

**Comment by olblak** [comment]
@mprzybylski This is something I am investigating with no ETA.
I am using the [go-git](https://github.com/go-git/go-git) library but it doesn't provide merge or rebase atm so I would need to either contribute that feature to go-git or come with something specific to Updatecli.

**Comment by olblak** [comment]
For record I am monitoring these two  issues:

* https://github.com/go-git/go-git/issues/942
* https://github.com/go-git/go-git/issues/905

The rebase sounds more complex and I would need to find enough "consecutive" quality time to work on it

**Comment by olblak** [comment]
I started working on this issue and I identify to area to improve.

1. Git operation
2. Pull request body

## Git

As a first iteration, I am checking by default if the latest commit of the base branch (main for example ) is a common ancestor of the working branch (updatecli_something). 
If not then we recreate the working branch based on the latest base branch.

It's not really a rebase operation because commits previously created by Updatecli on the working branch are discarded and then recreate by Updatecli if needed but at least we'll be able to start fresh from older branch.

My first design open question, how to specify that it's ok for Updatecli to force push the new changes. I am inclined to not introduce a parameter but instead relying on the `force` setting available to all scm provided as mentioned here  https://www.updatecli.io/docs/plugins/scm/gitea/

Today by default `force` would remain to false, and we could in a future version of Updatecli switch to true by default. My biggest fear is, if by default `force` is set to true then someone could shoot himself in the feet with a manifest like:  

```
scms:
  default:
    kind: github
    spec:
      owner: org
      repository: example
      workingbranch: false
      branch: main

targets:
  default:
    kind: yaml
    scmid: default
    spec:
      file: example.yaml
      key: "$.name"
      value: "foo"

```

Where the combination of `force`, `workingbranch`, and `branch` would allow forcing pushing to the main branch which is bad but could also be a valid use case in some situation...

## Pullrequest

The second area that requires is the pull request body created by Updatecli. If the branch was reset then we also need to reset the pull request body with the latest changes.

And here is a chicken and the egg problem

Today, we first execute all targets before actions. Git operation are done in the target, while pull requests are handled in actions. So during the delta between the target and action, the pull request won't reflect the real content...

As suggested by @dduportal , we could move git push operation closer to action to reduce the delta.
Another option would be to always execution a target in "dry run" mode to first identify if a change is needed and if yes then we update the pull request body with a warning, we update the target, and we update the pull request with the new content.

IMHO as first iteration, I'll try to keep this part as simple as possible and I will just reset the pull request body.

**Comment by olblak** [comment]
More I think about the force parameter and more I think it should remain false by default but we could set to true by default in shareable policies like those defined on https://github.com/updatecli/policies
