### ISSUE TITLE
Allow Sem Ver filtering

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#175]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I would like to be able to retrieve the "latest" version with a semver filter.

For instance "Retrieve the latest `1.14.*` for golang": let's say `1.14.15`. As for today, the "latest" `*` being `1.15.7`.

**Describe alternatives you've considered**

- Dependabot has this feature which make it pretty useful
- In term of pure "continuous update", then the digest of the latest docker image `1.15` could be used if we keep using updating docker `FROM` instruction. but we loose the information as a build argument (cant' use a label `go.version` for
 instance)

**Additional context**
Nope

**Comment by olblak** [comment]
After looking at the code [here](https://github.com/updatecli/updatecli/blob/main/pkg/plugins/github/source.go#L54L80), it's seems that it maybe easier than expected, at the moment we retrieve the latest 5 releases, and we pick the first one which is not a pre-release or a draft. Instead, we could retrieve every releases then sort them like done for jenkins releases. 
This would also be a good opportunity to add three new parameters so we could select if we consider `pre-release`, `release`, `draft`.

**Comment by olblak** [comment]
https://github.com/Masterminds/semver

**Comment by olblak** [comment]
This library sounds awesome, and all we need :smile:
