### ISSUE TITLE
Do not mention contributors

### ISSUE THREAD

**Issue by daniel-beck** [updatecli/updatecli#184]
Everyone writing code that makes it into a release is mentioned in PRs like https://github.com/jenkins-infra/charts/pull/882, and mentions create notifications. It seems for no real reason other than maybe credit?

Could you remove author mentions, or at least code-format them (e.g. `@daniel-beck`)?

**Comment by olblak** [comment]
Thanks for the suggestion and I'll try to find a solution. I am thinking out loud but since that changelog is automatically retrieved maybe one of the solutions would be to not be listed in the changelog. But for now, the easier solution seems to escape changelogs

**Comment by daniel-beck** [comment]
If you can find the changelog, you can link there, like Dependabot does, instead of inlining it.
