### ISSUE TITLE
Feature Request: rename `update-compose.yaml` for `updatecli-compose.yaml`

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#2284]
### Is your feature request related to a problem?

Help newbies understand the tool behind using the `update-compose.yaml` without the need to add any comments to explain the tool behind 

### Solution you'd like

Normalise the composable policies file's name to match the tool's name.

### Alternatives you've considered

Add a comment in the file, see https://github.com/elastic/apm-agent-nodejs/pull/4121#discussion_r1666982778

**Comment by olblak** [comment]
Thanks for great feedback, when I started working on this feature, I hesitated between having a more generic name like "update-compose.yaml" versus a more specific one like "updatecli-compose.yaml".

I agree with you that for new comer "updatecli-compose.yaml" is more obvious about the purpose.

**Comment by olblak** [comment]
This pullrequest https://github.com/updatecli/updatecli/pull/2291 handle both "updatecli-compose.yaml" and "update-compose.yaml"

If both are found, then it fallback to the previous behavior

```
 ~/Projects/Updatecli/updatecli │ on issue/2284: ./bin/updatecli compose show                                                                                                                                 ✔ │ took 12s 
WARN[0000] Deprecated default compose file "update-compose.yaml" detected. Please rename it to "updatecli-compose.yaml" 
WARN[0000] Both default compose files "update-compose.yaml" and "updatecli-compose.yaml" detected. Please remove "update-compose.yaml" to start using "updatecli-compose.yaml" 

```
