### ISSUE TITLE
Feature Request: autodiscovery for updatecli policies to support changelog

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#2286]
### Is your feature request related to a problem?

It's not possible to know what's the changelog for the updatecli policies when using the autodiscovery

### Solution you'd like

I want to see https://github.com/updatecli/udash/pull/93, which contains the changelog

**Comment by v1v** [comment]
I tried this recently but I cannot see any changelog entries.

See https://github.com/updatecli/policies/pull/37 and https://github.com/updatecli/policies/blob/e19fb988c3c89f0ea920f5fed984744d47da175f/updatecli/policies/autodiscovery/updatecli/Policy.yaml#L8

Hence, IIUC https://github.com/elastic/oblt-actions/pull/130/files should contain the Changelog entry but it's not there, the updatecli execution can be seen below:

```bash
VERSION

Application:	0.82.0
Golang     :	1.[22](https://github.com/elastic/oblt-actions/actions/runs/10954018309/job/30415241169#step:6:25).5 linux/amd64
Build Time :	20[24](https://github.com/elastic/oblt-actions/actions/runs/10954018309/job/30415241169#step:6:27)-08-04T10:30:55Z

Run updatecli --experimental compose apply
...

SOURCES
=======

version
-------
Searching for version matching pattern "*"
✔ Docker Image Tag "0.8.0" found matching pattern "*"


CHANGELOG:
----------
- Configure Pull Request GitHub labels using `labels`.

digest
------
✔ Docker Image Tag ghcr.io/updatecli/policies/autodiscovery/updatecli:0.8.0 resolved to digest ghcr.io/updatecli/policies/autodiscovery/updatecli:0.8.0@sha256:99e9e61b501575c2c176c39f2275998d198b590a3f6b1fe829f7315f8d457e7f

```

any hints what's the missing piece in my end?

**Comment by olblak** [comment]
+1 with the recent changes on the policies, I also faced de same problem.

I would like to change the approach to have something that could work for Docker images as well
