### ISSUE TITLE
Misleading message "wrong semantic version input: patch"

### ISSUE THREAD

**Issue by iurly** [updatecli/updatecli#2407]
This [line of code](https://github.com/updatecli/updatecli/blob/d26f1904ea387a5535f10d1977998d7fabb50a68/pkg/core/transformer/main.go#L146-L149)
prints `semVerInc` whenever `input` fails semantic version verification.
So the value of `input` should be printed instead.

**Comment by olblak** [comment]
Good catch @iurly , could you open a pullrequest?
