### ISSUE TITLE
gitlab merge requests error

### ISSUE THREAD

**Issue by WladyX** [updatecli/updatecli#2429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a merge request for gitlab, browsing to it:
- gitlab says: "Your merge request is almost ready!"
- browsing to Changes tab says: "Building your merge request… This page will update when the build is complete."

### Expected Behavior

The MR should not have any issues

### Steps To Reproduce

- create updatecli.d/manifest2.yaml file from below
- run `updatecli apply`

### Environment

```markdown
- OS: macos
- updatecli:


# manifest.yaml
name: QuickStart example

# Defines how to get "source" information such as Jenkins version
sources:
  lastRelease:
    kind: "helmchart"
    spec:
      url: "https://prometheus-community.github.io/helm-charts"
      name: "kube-prometheus-stack"

conditions: {}

# Defines "targets" which need to be updated if different than "source" information.
targets:
  tf_file:
    name: Bump Jenkins Docker Image Tag
    kind: hcl
    scmid: gitlab
    spec:
      file: "tf/harbor_replication_tkps.tf"
      path: resource.harbor_replication.repl_tkps_helm_prometheus.filters.tag
 
actions:
  default:
    title: Bump axios version4
    kind: gitlab/mergerequest
    scmid: gitlab    

scms:
  gitlab:
    kind: gitlab
    spec:
      owner: "wxs"
      url: "https://gitlab.domain.com"
      repository: "k8s/harbor"
      branch: main
      # For the change to be apply, we need to specify gitlab credentials
      username: wladyx
      token: glpat-private
```
### Anything else?

- i don't have the repo under my user, i have a group (wxs) maybe this is causing the issue?
- when i look at the commits history there is no name for the author and no email, maybe this is causing the issue?

in the browser console i see 404 for:
https://gitlab.domain.com/wxs/k8s/harbor/-/merge_requests/9/diffs_batch.json
in the gitlab logs i see:
```
{"content_type":"application/json","correlation_id":"01J47CCR4B5FC8Y1Y5MQ9D70T2","duration_ms":296,"host":"gitlab.domain.com","level":"info","method":"GET","msg":"access","proto":"HTTP/1.1","referrer":"https://gitlab.domain.com/wxs/k8s/harbor/-/merge_requests/9/diffs","remote_addr":"188.26.61.185:0","remote_ip":"188.26.61.185","route":"","status":404,"system":"http","time":"2024-08-01T16:29:27Z","ttfb_ms":295,"uri":"/wxs/k8s/harbor/-/merge_requests/9/diffs_metadata.json?diff_head=true\u0026view=inline\u0026w=0","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36","written_bytes":0}
172.17.0.1 - - [01/Aug/2024:16:29:27 +0000] "GET /wxs/k8s/harbor/-/merge_requests/9/diffs_metadata.json?diff_head=true&view=inline&w=0 HTTP/1.1" 404 31 "https://gitlab.domain.com/wxs/k8s/harbor/-/merge_requests/9/diffs" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" 0.00
{"component":"gitaly.StreamServerInterceptor","correlation_id":"01J47CD3ETEQ13A65N2CNV64S3","grpc.meta.auth_version":"v2","grpc.meta.client_name":"gitlab-workhorse","grpc.meta.deadline_type":"none","grpc.meta.method_operation":"accessor","grpc.meta.method_scope":"repository","grpc.meta.method_type":"server_stream","grpc.method":"InfoRefsUploadPack","grpc.request.fullMethod":"/gitaly.SmartHTTPService/InfoRefsUploadPack","grpc.request.glProjectPath":"wxs/k8s/radarr","grpc.request.glRepository":"project-80","grpc.request.repoPath":"@hashed/48/44/48449a14a4ff7d79bb7a1b6f3d488eba397c36ef25634c111b49baf362511afc.git","grpc.request.repoStorage":"default","grpc.service":"gitaly.SmartHTTPService","grpc.start_time":"2024-08-01T16:29:39.632","level":"info","msg":"getting stream","pid":1417,"remote_ip":"172.17.0.1","span.kind":"server","stream_path":"/var/opt/gitlab/git-data/repositories/+gitaly/cache/37/ea2a37cb5c5cc3722bb47798b2d839d86f3712404ea66cc29cf26d579f3dcc","system":"grpc","time":"2024-08-01T16:29:39.635Z","user_id":"user-11","username":"group_9_bot_c1d32da1c6614092276b8755515f8249"}
```

**Comment by WladyX** [comment]
That's great (that you were able to replicate) !
Let me know if/when you need some testing on my end.
Thank you!

**Comment by olblak** [comment]
I had another look, and I couldn't even create the pullrequest using curl from the API, still the same 400 errors but doing it from the UI worked...

**Comment by WladyX** [comment]
renovate works, maybe take a peek at their code?

**Comment by olblak** [comment]
I am adding this issue in the pipe.
Normally it should be working as I am using a popular library to interact with GitLab api
https://github.com/drone/go-scm

**Comment by WladyX** [comment]
Thank you @olblak ! Looking forward to start using this, I find it much easier than renovate for custom stuff.

**Comment by olblak** [comment]
I found what's wrong with the GitLab plugin.
The library that I am using go-scm is passing the merge request parameter via the URL instead of using a jsonbody [cfr](https://github.com/drone/go-scm/blob/44424ac1e91856e895c4c91283932ba2dea4bc01/scm/driver/gitlab/pr.go#L68)

This means that if the merge request description is too long which happens quickly if it contains changelog then the merge request fails.

I'll see if that library accept a contribution

**Comment by olblak** [comment]
I am trying to fix this issue upstream https://github.com/drone/go-scm/pull/322

**Comment by olblak** [comment]
Can you confirm you didn't encounter the issue with the version 0.110.0 and 0.110.1

**Comment by olblak** [comment]
I just gave it a try and GitLab works for me

https://gitlab.com/olblak/updatecli/-/merge_requests/1243 

This is a console output specific to the merge request creation
```
ACTIONS
========

---
Pipeline Name	: deps(go): bump module github.com/go-git/go-git/v5
Pipeline ID	: 92598acef8b96953c615436f65057a013ec5135d8b61f41efe3cf5b8bb44c271
Dry run		: false
Repository	: gitlab.com/olblak/updatecli@main
Action		: deps(go): bump module github.com/go-git/go-git/v5 to v5.16.3
---

GitLab mergerequest successfully opened on "https://gitlab.com/olblak/updatecli/-/merge_requests/1243"

---
Pipeline Name	: deps(go): bump module github.com/spf13/cobra
Pipeline ID	: bf224dbfaaa2b8f0fc97b0aea6e94b40687c3c3b454d34a78f768338b77fc807
Dry run		: false
Repository	: gitlab.com/olblak/updatecli@main
Action		: deps(go): bump module github.com/spf13/cobra to v1.10.1
---

GitLab mergerequest successfully opened on "https://gitlab.com/olblak/updatecli/-/merge_requests/1244"

```

@SSvilen I propose to an open a new issue because I am expecting to be different from the current one.

**Comment by SSvilen** [comment]
@olblak  The merge requests are being created. But we observe the same behaviour described by @vtmocanu in the issue description.

<img width="974" height="403" alt="Image" src="https://github.com/user-attachments/assets/73bc606c-e027-47e3-b9de-354bc316687a" />

<img width="825" height="22" alt="Image" src="https://github.com/user-attachments/assets/877927d7-7711-4b5c-b8f2-44e1d1c3d62d" />

I've tried:
- using the branch created by updatecli to manually create a merge request - same problem
- I've checkup the branch created by updatecli, made changes, pushed, tried creating a merge request - same problem
- I've manually created a branch with the same name - no problems observed

So the problem seems to be with the branch creation I guess...
