### ISSUE TITLE
Feature Request: pre-commit autodiscovery

### ISSUE THREAD

**Issue by reakaleek** [updatecli/updatecli#2431]
### Is your feature request related to a problem?

I want to update the hooks in the `pre-commit-config.yaml`

### Solution you'd like

Similar to https://www.updatecli.io/docs/plugins/autodiscovery/npm/

### Alternatives you've considered

- github release source + yaml target
- `pre-commit autoupdate` command
- [renovate pre-commit](https://docs.renovatebot.com/modules/manager/pre-commit/)

### Anything else?

https://pre-commit.com/#2-add-a-pre-commit-configuration

**Comment by olblak** [comment]
Interesting, I think it would make sense
