### ISSUE TITLE
Feature Request: Autodiscovery plugin for Hashicorp Nomad container jobs

### ISSUE THREAD

**Issue by landmass-deftly-reptile-budget** [updatecli/updatecli#2500]
### Is your feature request related to a problem?

Well, I would not call it a "problem" but a missing feature, at least from my point of view.

### Solution you'd like

I would like to be able to use updatecli for Hashicorp Nomad docker/container jobs, basically the same functionality already available for docker-compose, Kubernetes etc.
What is Hashicorp Nomad? It is another scheduler like Kubernetes or Docker Swarm but from Hashicorp.
[https://github.com/hashicorp/nomad](https://github.com/hashicorp/nomad
)
A simple example of a Nomad docker/container job is available in the Nomad documentation:
[https://developer.hashicorp.com/nomad/docs/job-specification/job#job-examples](https://developer.hashicorp.com/nomad/docs/job-specification/job#job-examples
)
The example is without a tag aka "latest" but in general it works like docker, docker-compose etc.
So we are talking about this value which needs to get parsed.
**image = "hashicorp/terraform:1.9.4"**

### Anything else?

It would be awesome to have this functionality available in updatecli.
First thank you very much for your work, this tool is a huge time saver and makes life easy.
I already use it for Dockerifle, Terraform and some Github release updates.

**Comment by dduportal** [comment]
Hi @landmass-deftly-reptile-budget , that feature request make sense!

For what it is worth, on short term, you should be able to start using the [HCL](https://www.updatecli.io/docs/plugins/resource/hcl/) resources since Nomad uses this language for defining setups as per https://developer.hashicorp.com/nomad/docs/configuration.

There are not auto-discovery, but it could help you setting up a first `updatecli` lifecycle on a few selected items.

**Comment by olblak** [comment]
Thanks for opening this issue, do you think it is different from https://github.com/updatecli/updatecli/issues/2331 ?

An autodiscovery plugin, just analyze files and generate Updatecli manifest. So if we already have all the declarative plugins implemented then it becomes trivial to implement an new autodiscovery plugin.

In the context of Nomad, I think we already have all the plugins so could I ask you different examples of Nomad config files that should be updated, so I can use them for test cases

Bonus point a git repository that I could have on GitHub.com/updatecli-test

**Comment by landmass-deftly-reptile-budget** [comment]
@olblak Thanks for the hint. Well, it looks like I did not do my research properly before opening this feature request.
I had this request in mind for a couple of month and did not see anything in this direction in the past.
#2331 is basically what I need/want.
I think we can close this request then.
