### ISSUE TITLE
Git submodule using git url syntax is failing

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#256]
**Describe the bug**
Updatecli can't clone git repository with git submodule using the git syntax.
Due to this, I had to switch from git to HTTP syntax in this [repository](https://github.com/jenkins-infra/status/pull/47)

**To Reproduce**
Revert this [PR](https://github.com/jenkins-infra/status/pull/47), and the try to run `updatecli diff --config updatecli/updatecli.d --values updatecli/values.yaml` 

**Expected behavior**
It should work.

**Screenshots**

**Version (please complete the following information):**
 - Version: v0.6.0

**Additional context**
/

**Comment by dduportal** [comment]
Just tested again with updatecli 0.18.3 and it works without any error. Closing unless we can reproduce.
