### ISSUE TITLE
Keep GitHub Actions up to date

### ISSUE THREAD

**Issue by lemeurherveCB** [updatecli/updatecli#2760]
### Is your feature request related to a problem?

There is currently nothing updating the GHA versions cf #2759 

### Solution you'd like

Add updatecli manifests to track their versions and keep them updated

### Alternatives you've considered

renovabot :trollface: 

### Anything else?

https://github.com/updatecli/updatecli/pull/1964 could help.

**Comment by olblak** [comment]
GitHub action update are maintained by Dependabot [cfr](https://github.com/updatecli/updatecli/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Fdependabot)

Until  I find time to finish this pullrequest https://github.com/updatecli/updatecli/pull/1964 :)

**Comment by lemeurherveCB** [comment]
Any idea why it didn't catch #2759 ?

**Comment by olblak** [comment]
> Any idea why it didn't catch #2759 ?

I was but at some point I had to rollback because the new version failed.
cfr https://github.com/updatecli/updatecli/pull/1640

**Comment by olblak** [comment]
I really like this project but I find it difficult to test locally
