### ISSUE TITLE
sigsev with forgejo and oauth2 token

### ISSUE THREAD

**Issue by btrepp** [updatecli/updatecli#2802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x87a0c8]

goroutine 1 [running]:
github.com/updatecli/updatecli/pkg/plugins/resources/gitea/pullrequest.(*Gitea).isPullRequestExist(0x400037e2a0)
        /home/runner/work/updatecli/updatecli/pkg/plugins/resources/gitea/pullrequest/utils.go:38 +0x1b8
github.com/updatecli/updatecli/pkg/plugins/resources/gitea/pullrequest.(*Gitea).CreateAction(0x400037e2a0, {{0x40012a7b40, 0x40}, {0x4000e657f0, 0xe}, {0x4000e657f0, 0xe}, {0x0, 0x0}, {0x40012f66e0, ...}, ...}, ...)
        /home/runner/work/updatecli/updatecli/pkg/plugins/resources/gitea/pullrequest/create.go:37 +0x15c
github.com/updatecli/updatecli/pkg/core/pipeline.(*Pipeline).RunActions(0x4001060750)
        /home/runner/work/updatecli/updatecli/pkg/core/pipeline/actions.go:150 +0x934
github.com/updatecli/updatecli/pkg/core/engine.(*Engine).runActions(0x54ff460)
        /home/runner/work/updatecli/updatecli/pkg/core/engine/actions.go:22 +0x1c4
github.com/updatecli/updatecli/pkg/core/engine.(*Engine).Run(0x54ff460)
        /home/runner/work/updatecli/updatecli/pkg/core/engine/run.go:25 +0x290
github.com/updatecli/updatecli/cmd.run({0x2fc718e?, 0x0?})
        /home/runner/work/updatecli/updatecli/cmd/root.go:101 +0xb98
github.com/updatecli/updatecli/cmd.init.func5(0x54b1d40?, {0x40009826c0?, 0x0?, 0x2?})
        /home/runner/work/updatecli/updatecli/cmd/apply.go:47 +0x234
github.com/spf13/cobra.(*Command).execute(0x54b1d40, {0x40009826a0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0x81c
github.com/spf13/cobra.(*Command).ExecuteC(0x54b11c0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/updatecli/updatecli/cmd.Execute()
        /home/runner/work/updatecli/updatecli/cmd/root.go:49 +0x68
main.main()
        /home/runner/work/updatecli/updatecli/main.go:8 +0x1c
```

### Expected Behavior

Pull request opened

### Steps To Reproduce

```
actions: gitea: {
	scmid: "forgejo"
	kind: "gitea/pullrequest"
}
```

### Environment

```markdown
- OS:

cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.20.3
PRETTY_NAME="Alpine Linux v3.20"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"

- updatecli:
updatecli version

VERSION

Application:    0.85.0
Golang     :    1.23.2 linux/amd64
Build Time :    2024-10-07T06:48:15Z
```

### Anything else?

https://forgejo.org

While forejo is a fork, I would imagine the pull request api wouldn't have diverged.
Worst case, I would expect updatecli to return a bit of an error about what happened, instead of crashing entirely

**Comment by btrepp** [comment]
https://github.com/updatecli/updatecli/blob/d71451b35ef47a7e89b200f404538c5d544aa35b/pkg/plugins/resources/gitea/pullrequest/utils.go#L38

So that's that line, I imagine resp is probably nil in the case that an error is returned, so ironically trying to log debug information causes the crash :D

**Comment by btrepp** [comment]
Changing the scm block spec to a API token does make it work. However I still would like to get oauth2 tokens working somehow.

**Comment by btrepp** [comment]
Okay. After attaching a debugger. I think I have gotten to this point.


https://www.updatecli.io/docs/plugins/actions/gitea/ is slightly misleading, it says 'token' is an option, but it appears the gitea pull request action is basically driven from the SCM block, including the auth. So even if I specify the token here, I am getting the clone token anyway, annoyingly these seem to be slightly different in what gitea requires.

Eg a git clone, the oauth2 token is fine, and will work.

What's odd in curl, prefixing token, or bearer works. So now I can only think it's actually something in the http stack validating that http header, and failing before the http call.

**Comment by olblak** [comment]
A few things,

> it says 'token' is an option, but it appears the gitea pull request action is basically driven from the SCM block

By default, all actions inherits parameters from the link scmid, for example the action `gitea/pullrequest` inherits default parameters from the scm `gitea`.

cfr https://github.com/updatecli/updatecli/blob/d71451b35ef47a7e89b200f404538c5d544aa35b/pkg/plugins/resources/gitea/pullrequest/main.go#L48

 > The only thing I don't really understand here is why a normal gitea token works

All API requests relies on a oauth2 token as defined on 
https://github.com/updatecli/updatecli/blob/d71451b35ef47a7e89b200f404538c5d544aa35b/pkg/plugins/resources/gitea/client/main.go#L26

While by default git operation are done via basic auth http request
[cfr](https://github.com/updatecli/updatecli/blob/d71451b35ef47a7e89b200f404538c5d544aa35b/pkg/plugins/utils/gitgeneric/main.go#L82)
