### ISSUE TITLE
Feature Request: honour CI debugging flags

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#2805]
### Is your feature request related to a problem?

Sometimes I need to debug what's going on when running `updatecli` using GitHub actions, for such, I need to enable `--debug` through a GH Pull Request so I can try again what's going on.

I don't want to set `--debug` by default unless something goes side-wides.

### Solution you'd like

I want to benefit from https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging or its UI click-ops analogy. 

<img width="710" alt="image" src="https://github.com/user-attachments/assets/74d85f5e-f7e4-4d44-92cc-a97796129ff6">

So `updatecli` could detect if the environment variable called `ACTIONS_RUNNER_DEBUG` is set, and if so, then honour the `--debug` flag.

This will let me test things without the need to change/add/commit/push/review process.

**Comment by olblak** [comment]
Thanks for the suggestion, I like it very much.
I agree with that by default we shouldn't run Updatecli in debug mode as it may leak important information.

Your suggestion sounds easy to do as we could just implemented a switch case on https://github.com/updatecli/updatecli/blob/d71451b35ef47a7e89b200f404538c5d544aa35b/cmd/root.go#L59

IMHO it would be interesting to have something similar for Jenkins, GitLab CI, etc.

**Comment by v1v** [comment]
PR: https://github.com/updatecli/updatecli/pull/2822
