### ISSUE TITLE
The Adoptium API has changed the location header

### ISSUE THREAD

**Issue by gounthar** [updatecli/updatecli#2839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the debug mode, I can see `DEBUG: [temurin] API client got the following Location header value: "".`
It makes me think of the [discussion](https://adoptium.slack.com/archives/C09NLQQAV/p1728223668491699?thread_ts=1728128855.456059&cid=C09NLQQAV) Mark Waite and the Temurin team got about the recent changes due to the CloudFlare usage.

```
CONDITIONS:
===========

checkTemurinAlpineRelease
-------------------------
DEBUG: [temurin] Performing an http GET request to "https://api.adoptium.net/v3/types/architectures"...
DEBUG: [temurin] API client returned the following response:
&{200 OK 200 HTTP/2.0 2 0 map[Alt-Svc:[h3=":443"; ma=86400] Cf-Cache-Status:[DYNAMIC] Cf-Ray:[8d365b2e7bd299d9-CDG] Content-Type:[application/json;charset=UTF-8] Date:[Wed, 16 Oct 2024 07:32:38 GMT] Server:[cloudflare] Strict-Transport-Security:[max-age=63072000; includeSubDomains; preload] X-Content-Type-Options:[nosniff] X-Frame-Options:[DENY] X-Pod-Hostname:[frontend-service-f6979b64b-zgv68]] 0xc00126c2a0 -1 [] false true map[] 0xc001034c80 0xc0011f20c0}
DEBUG: [temurin] API client got the following Location header value: "".
DEBUG: [temurin] Performing an http GET request to "https://api.adoptium.net/v3/types/operating_systems"...
DEBUG: [temurin] API client returned the following response:
&{200 OK 200 HTTP/2.0 2 0 map[Alt-Svc:[h3=":443"; ma=86400] Cf-Cache-Status:[DYNAMIC] Cf-Ray:[8d365b2f3c6d99d9-CDG] Content-Type:[application/json;charset=UTF-8] Date:[Wed, 16 Oct 2024 07:32:39 GMT] Server:[cloudflare] Strict-Transport-Security:[max-age=63072000; includeSubDomains; preload] X-Content-Type-Options:[nosniff] X-Frame-Options:[DENY] X-Pod-Hostname:[frontend-service-f6979b64b-zgv68]] 0xc0010c2fc0 -1 [] false true map[] 0xc001034f00 0xc0011f20c0}
DEBUG: [temurin] API client got the following Location header value: "".
✗
```

### Expected Behavior

Not such a warning.

### Steps To Reproduce

1. Clone https://github.com/gounthar/docker.git
2. Checkout the `adoptium-source` branch
3. `updatecli diff --debug --config ./updatecli/updatecli.d/jdk21.yaml --values ./updatecli/values.github-action.yaml 2>&1`

### Environment

```markdown
- OS: WSL2/Debian
- updatecli: 0.85.0
```

**Comment by dduportal** [comment]
I'm note sure (at least not yet: work in progress) if the condition failing is expected or not:

- If it is, then we need to improve the user feedback on the adoptium plugin in updatecli
- If it is not, I'm not sure to understand it.

2 points though @gounthar:

- Could you quote the discussion you mentioned? Your link is to a Slack conversation that I cannot see: it requires creating an account and joining the spaces, etc.. So it's not really discoverable (sorry to be that person.. ;) )
- Your [manifest](https://github.com/gounthar/docker/blob/2353803ff5fad52db4b48429ddc394414f98bfa6/updatecli/updatecli.d/jdk21.yaml#L22-L29) has mistakes:
  - The architectures you specified are invalid for Temurin API (they are "Docker like" with both operating system and CPU arch combined). Temurin uses splitting formats (separating operating system and arch. for instance).
    - The doc. specifies examples: https://www.updatecli.io/docs/plugins/resource/temurin/#_parameter
    - I'm not sure if it is easy to detect such a failing keyword when executing updatecli. Ping @olblak : do you think `updateccli diff` could run a json validation and prints warnings as part of the run?
  - the keyword `architectures` (plural form) is not supported: it's not documented in https://www.updatecli.io/docs/plugins/resource/temurin/#_parameter (and if you use a text editor with support for JSON schema, it will set the attribute in red as it's not supported). Worth a feature request (legit for a condition to simplify manifest writing) issue, but not an easy one unless we start supporting "Docker style" (see point above), otherwise it would be a matrix with 2 axes (OS and arch) which would be hard to specify for the user. Maybe using `platform` could improve the user experience.

**Comment by gounthar** [comment]
> Mark Waite
>   Le 5 oct. à 13 h 47
> https://api.adoptium.net/v3/binary/version/jdk-17/alpine-linux/x64/jdk/hotspot/normal/eclipse?project=jdk is responding with HTTP 404 and causes the container image builds of the Jenkins project to fail.  Refer to [ci.jenkins.io](https://ci.jenkins.io/job/Packaging/job/docker/job/master/) for failing job
> https://status.adoptium.net/ redirects to Atlassian statuspage without reporting any status information related to [Adoptium.net](http://adoptium.net/)
> AtlassianAtlassian
> [Improve Transparency with Statuspage | Atlassian](https://status.adoptium.net/)
> Statuspage provides real-time incident communication and status updates. Keep customers informed, build trust, and enhance transparency. Start now!
> 
> 
> 
> NOUVEAU
> 
> 13 réponses
> 
> 
> Mark Waite
>   [Le 5 oct. à 13 h 56](https://adoptium.slack.com/archives/C09NLQQAV/p1728129362090709?thread_ts=1728128855.456059&cid=C09NLQQAV)
> The default values from the https://api.adoptium.net/q/swagger-ui/#/Binary/getBinaryByVersion page also report HTTP 404
> 
> 
> gdams
> :microsoft:  [Le 6 oct. à 14 h 16](https://adoptium.slack.com/archives/C09NLQQAV/p1728217007618489?thread_ts=1728128855.456059&cid=C09NLQQAV)
> I’ve fixed the status page, looking into your API issues now
> [14 h 19](https://adoptium.slack.com/archives/C09NLQQAV/p1728217198789009?thread_ts=1728128855.456059&cid=C09NLQQAV)
> Looking at your request, I don’t think it’s valid. If you want a specific version of JDK17 you’d need to use this:
> https://api.adoptium.net/v3/binary/version/jdk-17.0.12+7/alpine-linux/x64/jdk/hotspot/normal/eclipse?project=jdk
> otherwise you can get the latest version like this
> https://api.adoptium.net/v3/binary/latest/17/ga/alpine-linux/x64/jdk/hotspot/normal/eclipse?project=jdk
> 
> 
> Mark Waite
>   [Le 6 oct. à 14 h 21](https://adoptium.slack.com/archives/C09NLQQAV/p1728217290357449?thread_ts=1728128855.456059&cid=C09NLQQAV)
> Thanks for investigating.  Interesting that the request was valid and returning the results we needed until a few days ago.
> 
> 
> gdams
> :microsoft:  [Le 6 oct. à 14 h 21](https://adoptium.slack.com/archives/C09NLQQAV/p1728217318638589?thread_ts=1728128855.456059&cid=C09NLQQAV)
> hmm strange, CC 
> [@johno](https://adoptium.slack.com/team/U53BTMDN3)
>  who might be able to tell us if something has changed
> 
> 
> Mark Waite
>   [Le 6 oct. à 14 h 40](https://adoptium.slack.com/archives/C09NLQQAV/p1728218415745119?thread_ts=1728128855.456059&cid=C09NLQQAV)
> I think that I may understand the difference.  It appears that our download script is parsing HTTP headers with shell commands and is looking for the word "Location" instead of a case insensitive "location".  The response is now an HTTP/2 307 with a "location" where previously it was "Location".  As far as I can tell, the fix needs to come from our side, not your side.  Thanks again for providing the API! (modifié) 
> :+1:
> 1
> 
> 
> 
> Mark Waite
>   [Le 6 oct. à 14 h 53](https://adoptium.slack.com/archives/C09NLQQAV/p1728219182755109?thread_ts=1728128855.456059&cid=C09NLQQAV)
> I've submitted the pull request to resolve the issue in our code.  Refer to https://github.com/jenkinsci/docker/pull/1936
> [#1936 fix: Adapt to recent changes in JDK download URL response](https://github.com/jenkinsci/docker/pull/1936)
> fix: Adapt to recent changes in JDK download URL response
> Parse the JDK redirect URL for a case insensitive redirect location
> [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307) shows the HTTP 307 response as:
> location: /en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data  
> content-type: text/plain; charset=utf-8  
> date: Fri, 19 Jul 2024 12:57:17 GMT
> Previously, the response must have used "Location:" rather than "location:"
> Include URL in download failure error message
> Much easier to diagnose failures if the requesting URL is included in the message. Since the failure will end that portion of the build job, the extra verbosity is not additionally harmful.
> Testing done
> Confirmed that make build fails without this chang… En afficher plus
> Labels
> bug
> <https://github.com/[jenkinsci/docker](https://github.com/jenkinsci/docker)|jenkinsci/docker>jenkinsci/docker | 6 oct. | Ajouté(e) par [GitHub](https://adoptium.slack.com/services/B02008NKMLG)
> :+1::couleur-de-peau-3::+1:
> 2
> 
> 
> 
> johno
>   [Le 6 oct. à 15 h 44](https://adoptium.slack.com/archives/C09NLQQAV/p1728222253978829?thread_ts=1728128855.456059&cid=C09NLQQAV)
> the default values dont work as we give a bad default version, 11.0.6 was under AdoptOpenJDK so wont be distributed by Adoptium
> [15 h 48](https://adoptium.slack.com/archives/C09NLQQAV/p1728222482004399?thread_ts=1728128855.456059&cid=C09NLQQAV)
> interesting that it has changed from Location to location...presume that was a Quarkus change, but we have not changed the Quarkus version in some time, so if this is a recent failure that change must have come from elsewhere
> 
> 
> gdams
> :microsoft:  [Le 6 oct. à 15 h 56](https://adoptium.slack.com/archives/C09NLQQAV/p1728222967335089?thread_ts=1728128855.456059&cid=C09NLQQAV)
> I wonder if cloudflare changed this in some way?
> 
> 
> Mark Waite
>   [Le 6 oct. à 16 h 07](https://adoptium.slack.com/archives/C09NLQQAV/p1728223668491699?thread_ts=1728128855.456059&cid=C09NLQQAV)
> That could be it.  The redirect might have changed from one HTTP code to another (301 to 307) though in both cases, the Mozilla docs say that the header is "location:" but we were finding "Location:".  In any case, the problem was in our code and is now fixed in our code
> :+1::couleur-de-peau-3::+1:
> 2
> 
> 
> 
> gdams
> :microsoft:  [Le 6 oct. à 16 h 12](https://adoptium.slack.com/archives/C09NLQQAV/p1728223929760679?thread_ts=1728128855.456059&cid=C09NLQQAV)
> hmm the change to 307 doesn’t seem intended to me, I’ll check the cloudflare docs
> [16 h 14](https://adoptium.slack.com/archives/C09NLQQAV/p1728224057355499?thread_ts=1728128855.456059&cid=C09NLQQAV)
> I think that cloudflare is caching the response and so we’re seeing a 307 instead of a 301

**Comment by gounthar** [comment]
I apologize for submitting an incomplete issue. This experience has highlighted several areas for improvement in my approach:

1. **IDE Limitations**: My IDE (IntelliJ) doesn't properly handle the updatecli policy manifest, which led to some confusion.

2. **Documentation Adherence**: I should have trusted the written documentation rather than assuming it might be outdated. This is a reminder of the importance of following official guidelines.

3. **Syntax Confusion**: I mistakenly mixed the syntax used for Docker images (`linux/ppc64le`) with what is described in the updatecli documentation.

Despite these errors, this experience has revealed a potential area for enhancement in updatecli:

**Suggestion for updatecli Improvement**: 
We should maybe consider improving user feedback mechanisms in updatecli. As a user, I had the false impression that everything was proceeding normally. Clearer, more detailed status updates or warnings could help prevent similar misunderstandings in the future.

**Comment by olblak** [comment]
I don't know if it's related but the temurin e2e tests are now failing 

![image](https://github.com/user-attachments/assets/fa2984cb-4381-4bc8-aabb-ed3aa4ee3531)

**Comment by gounthar** [comment]
Damien helped me configure my JSON Schema in Intellij.
After launching `updatecli jsonschema` and referencing the schema within my IDE, I can now see my errors:
![image](https://github.com/user-attachments/assets/82f7c991-f947-4132-a390-874adcf9575a)

Thanks! 👍

**Comment by dduportal** [comment]
Update:

- the error in @gounthar in his attempts is unrelated to his syntax errors. It **is** related to the fact that conditions of type `temurin` do NOT exists.
  - Feature request opened in https://github.com/updatecli/updatecli/issues/2915
  - But there are no hard error when trying to have a condition or target of type temurin: I believe it is a bug (which I did creat by copy and pasting 😅) which should be fixed (incoming PR)
- Another bug, unrelated to this issue, was caught while pairing with @gounthar : https://github.com/updatecli/updatecli/issues/2914
- Last topic, but not least: @olblak do you have an example, in the documentation, of a command to ask `updatecli` if a given manifest is valid or not (even if it is only warnings)?

**Comment by dduportal** [comment]
PRs opened:

- https://github.com/updatecli/updatecli/pull/2916
- https://github.com/updatecli/updatecli/pull/2917
