### ISSUE TITLE
Feature Request [Resource "YAML"] allow condition to only check for existence of a key (and not the value)

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#289]
**Is your feature request related to a problem? Please describe.**

Let's consider the following YAML manifest: https://github.com/jenkins-infra/jenkins-infra/blob/958091069665a88a32a72e154e644d55f54e1b71/updatecli/weekly.d/buildmaster-tools.yaml#L70

I would like to add a condition that would check for the existence of the key in the YAML file.

The rationale is that as soon as #60 is implemented, then the execution would not fail when the key does not exist, leading to false positive (the key would be created and updatecli would report a success while the user would want to be notifieed of this as a failure because the YAML was changed recently but not updatecli manifest).

**Describe the solution you'd like**

Adding a new attribute `keyOnly` only available on the condition of kind "YAML", that would ignore the value and only check for the existence of the key.

**Describe alternatives you've considered**

- Using a shell condition with the command `yq`

**Additional context**
N.A.

**Comment by olblak** [comment]
That would definitely be usefull, I am pretty sure we could easily detect
