### ISSUE TITLE
Feature Request: allow to not exit on error when a condition fails

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#291]
**Is your feature request related to a problem? Please describe.**

I would like the ability to not exit an updatecli run with an error when some conditions are failing.

If you consider the updatecli manifest modified in https://github.com/jenkins-infra/jenkins-infra/pull/1898:

- It adds a condition to NOT open a pull request if the Maven binaries are not available
  * updatecli 0.7.1 is used, and the resulting behavior is correct: the conditon fails and the target is never executed, leading in NO PR trying to update the mavenVersion
  * BUT the associated Github Action workflow fails because `updatecli` reports an exit code different than 0 (because the conditions failed, hence the updatecli job is reported as failed.

It's annoying because the goal of calling `updatecli diff` on each commit/PR is to ensure that a change to the local file should not fail (unless there is a legit error of course), and act as a reminder to contributor that "hey please update updatecli manifest as well if you change a file that updatecli uses".

**Describe the solution you'd like**

- Keep the current internal behavior: the condition in my case still returns "false", the targets are not evaluated and the job reports "failed".
- But if the condition has the attribute `noFailure` set to `true` (default value is `false` to keep the curent behavior),
  then the exit code of `updatecli` should still be 0 if no other job failed.

**Describe alternatives you've considered**

- might be a flag to `updatecli diff` instead such as `--no-failure-by-conditions` (instead, or in addition to the proposed attribute)
- might be restricted to `updatecli diff`, or not

**Additional context**

Impleting this might be related to #233

**Comment by timja** [comment]
I hit this too, I don't think it needs a flag

**Comment by olblak** [comment]
> I hit this too, I don't think it needs a flag

Are you suggesting to not fail on conditions or just when doing a diff? I am facing the same issue as well and looking for feedback.
