### ISSUE TITLE
Piping output of `updatecli` commands not working

### ISSUE THREAD

**Issue by dalwar23** [updatecli/updatecli#2996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have tried several ways to `pipe` (`|`) updatecli command's output but it seems like it doesn't work. Output remains same same as the initial command.

### Expected Behavior

We would be able to pipe output of `updatecli` command and use utilities like `tail`, `grep`.

### Steps To Reproduce

1. Create an updatecli config with at least `source` and `target`
2. Run `updatecli diff` or `updatecli apply` and try to pipe the output to `tail` or `less` or `grep`

 ```shell
updatecli diff | grep "Run Summary" -A7
```

**Expected**

```shell
Run Summary
===========
Pipeline(s) run:
  * Changed:    1
  * Failed:     0
  * Skipped:    0
  * Succeeded:  1
  * Total:      2
```

**Actual**

- We get whole output of the command

### Environment

```markdown
- OS: Ubuntu 24.04
- updatecli: 0.86.1
```

**Comment by olblak** [comment]
Thanks for opening this issue. You are right by default Updatecli output to StdErr instead of StdOut.
It took me a long time to notice that but I must admit, it wasn't my priority.

The fix is easy but potentially a break change

**Comment by dalwar23** [comment]
Thank you for quick response. Much appreciated. I will try the following:

1. Try and catch the `stderr` (in shell)
2. Try redirecting `stderr` to `stdout` (in shell)

See if I can find a workaround for now. If you already know something, feel free to share.

**Comment by dduportal** [comment]
> Thank you for quick response. Much appreciated. I will try the following:
> 
>     1. Try and catch the `stderr` (in shell)
> 
>     2. Try redirecting `stderr` to `stdout` (in shell)
> 
> 
> See if I can find a workaround for now. If you already know something, feel free to share.

On short term, you should be able to redirect stderr to stdout which would do the trick:

```
updatecli diff 2>&1 | grep "Run Summary" -A7
```

**Comment by dalwar23** [comment]
@dduportal it worked. Thanks.
