### ISSUE TITLE
[file] error when applying a target with SCM

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#366]
**Describe the bug**
In https://github.com/jenkins-infra/pipeline-library/actions/runs/1453196383, the manifest uses a target of type "file" with scm.
When applied, the diff is OK, but it fails with the error

```
ERROR: Something went wrong in target "updateGroovyCode" :
ERROR: entry not found
```

**To Reproduce**

- Manifest: https://github.com/jenkins-infra/pipeline-library/blob/c5c4b2244c2995bf2153357a45dad6e9c7eda938/updatecli/updatecli.d/updatecli.yml
- Command: https://github.com/jenkins-infra/pipeline-library/blob/c5c4b2244c2995bf2153357a45dad6e9c7eda938/.github/workflows/updatecli.yaml

**Expected behavior**
- I expect no error (since it works as expected whithout scm but locally)

**Comment by dduportal** [comment]
Error comes from the `git` plugin: https://github.com/updatecli/updatecli/blob/main/pkg/plugins/git/generic/main.go#L65. Not sure why though.

**Comment by olblak** [comment]
I am wondering if it's a file path issue, like it tried to run git add from the wrong location

**Comment by dduportal** [comment]
> I am wondering if it's a file path issue, like it tried to run git add from the wrong location

Oh that could make sense since it happens with the file target that i changed recently. Be warned that if I messed up the target SCM, it might be the case with yaml target as well

**Comment by dduportal** [comment]
🤔 https://github.com/updatecli/updatecli/blob/main/pkg/plugins/file/target.go i cannot remember why is the « isAbs » method is called. Feel lile it would he the culprit

**Comment by dduportal** [comment]
Gotcha, you are correct @olblak:
- With `v0.12.0` (before my changes):
```text
DEBUG: adding file: vars/updatecli.groovy
```
- With `v0.14.0` (before my changes):
```text
DEBUG: adding file: /var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/dduportal/pipeline-library/vars/updatecli.groovy
```

Incoming fix

**Comment by dduportal** [comment]
Opened #368 which fixes the "path" part. But I got a new error:
```
DEBUG: stage: git-push

DEBUG: 
Create a pull request for 'updatecli_9650af5407cf9d62731a66c757a6fc795a7c3578123cf987b1b061f3526008a2' on GitHub by visiting:
     https://github.com/dduportal/pipeline-library/pull/new/updatecli_9650af5407cf9d62731a66c757a6fc795a7c3578123cf987b1b061f3526008a2

DEBUG: Updating Github pull request
DEBUG: GitHub Api credit used used 1, remaining 4956 (reset at 2021-11-13T10:11:13Z)
ERROR: Something went wrong in target "updateGroovyCode" :
ERROR: State cannot be changed. The updatecli_9650af5407cf9d62731a66c757a6fc795a7c3578123cf987b1b061f3526008a2 branch was force-pushed or recreated.
```
Diagnose in progress

**Comment by olblak** [comment]
> Opened #368 which fixes the "path" part. But I got a new error:
> ```
> DEBUG: stage: git-push
> 
> DEBUG: 
> Create a pull request for 'updatecli_9650af5407cf9d62731a66c757a6fc795a7c3578123cf987b1b061f3526008a2' on GitHub by visiting:
>      https://github.com/dduportal/pipeline-library/pull/new/updatecli_9650af5407cf9d62731a66c757a6fc795a7c3578123cf987b1b061f3526008a2
> 
> DEBUG: Updating Github pull request
> DEBUG: GitHub Api credit used used 1, remaining 4956 (reset at 2021-11-13T10:11:13Z)
> ERROR: Something went wrong in target "updateGroovyCode" :
> ERROR: State cannot be changed. The updatecli_9650af5407cf9d62731a66c757a6fc795a7c3578123cf987b1b061f3526008a2 branch was force-pushed or recreated.
> ```
> Diagnose in progress

Could it be related to my recent changes regarding pull request, previously I would just open and update open PR, now I also try to reopen a closed PR maybe there is something that I misunderstood in closed PR manipulation

**Comment by dduportal** [comment]
Might be, but it seems to be another issue than this one in the end (I was successful on the initial subject).

I'll try to open another issue with a reproduction case for the second error.

#368 is ready to review :)
