### ISSUE TITLE
Can't reopen pullrequest if associated branch was previously deleted

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#404]
**Describe the bug**
Updatecli tries to always reuse the same temporary branch name.
Since version 0.15.0,updatecli try to reopen closed pull request.
If we manually closed a pullrequest and delete the associated branch then the github API returns an error

**Steps to Reproduce**

1. Run updatecli
2. Closed the newly generated pullrequest
3. Delete the associated branch 
4. Re-run the same updatecli pipeline

**Expected behavior**
It should open a new pullrequest

**Screenshots**

**Version**

- OS: linux
- Updatecli version: 0.16.0

**Additional context**

**Comment by dduportal** [comment]
Not sure of the status of this issue => no milestone target for now.

@olblak I'm challenging the label as "bug". For me that would be an enhancement as the current behavior is wanted: do you agree?

**Comment by olblak** [comment]
As far as I remember, we fixed this issue as we don't try anymore to reopen an old pull request. Instead we open a new one.

**Comment by dduportal** [comment]
Oh good point. Let's close the issue then (we would reopen if we reproduce).
