### ISSUE TITLE
Change non absolute paths to resource to be relative to YML manifest instead of current working dir?

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#411]
**Is your feature request related to a problem?**
 
As underlined by @olblak in https://github.com/updatecli/updatecli/pull/388#issuecomment-991077726, the relative path for resources is resolved from the directory where the command `updatecli` command is run (e.g. the "current working directory").

This behavior is problematic as soon as you change this "current working dir": either you're browsing from a subdirectory or using absolute path:

```shell
$ tree /workspace
└── updatecli
    ├── config.yaml
    └── file.txt
## Success if there is a relative path such as `./updatecli/file.txt`
$ updatecli diff --config ./updatecli/config.yaml

## Doesn't work from subdir
$ cd ./updatecli/
$ updatecli diff --config ./updatecli/config.yaml ## fails

## Does'nt work from another dir even with absolute paths
$ PROJECT_DIR=$(pwd)
$ cd /tmp
$ updatecli diff --config ./updatecli/config.yaml ## fails
```

**Describe the solution you'd like**

It would make sense to resolve relative path from the YAML manifest files provided as config: it would solve all the issues here.

**However** that would break a lot of actual configurations.

**Describe alternatives you've considered**
N.A.

**Additional context**
Trying to be "smart" by trying to autodetect if the path would wether be "relative to manifest, otherwise to CWD" could be risky (weird "magical" code).

**Comment by lemeurherve** [comment]
Duplicated issue: https://github.com/updatecli/updatecli/issues/410

**Comment by dduportal** [comment]
Sounds like opening Gh issues in the train is not working as expected \o/
