### ISSUE TITLE
Remove deprecated field "source"

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#413]
**Is your feature request related to a problem?**
In version [0.2.0](https://github.com/updatecli/updatecli/releases/tag/v0.2.0), we deprecated the field `source` in favor of `sources` which allow to define multiple sources. We should remove all the code related to the transition from `source` to `sources`

**Describe the solution you'd like**
No mention of `source` including in documentation and example

**Describe alternatives you've considered**
/

**Additional context**
It would be nice to identify a way to remove deprecated fields sooner

**Comment by dduportal** [comment]
- I propose 0.20.0 milestone for this.
- I'm willing to take it (like #373)
- It needs #412 to be merged

**Comment by dduportal** [comment]
Closed by https://github.com/updatecli/updatecli/pull/589
