### ISSUE TITLE
Wrong pullrequest message

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#421]
**Describe the bug**
If we run `updatecli diff` the pullrequest message say "Nothing left to do as no target related to pullrequest "helm-charts" have changed" even if changed are needed 

**Steps to Reproduce**

**Expected behavior**

It should display what would happen

**Screenshots**
```
TARGETS
========

helm-chartss
------------

**Dry Run enabled**

INFO: Using spec.Value instead of source input value.
⚠ Key 'image.epinio.tag', from file '/tmp/updatecli/epinio/helm-charts/chart/epinio/values.yaml', was updated from '' to 'v0.3.1'


PULL REQUESTS
=============

Nothing left to do as no target related to pullrequest "helm-charts" has changed

=============================

REPORTS:


⚠ EPINIO.YAML:
	Sources:
		✔ [epinio] Get Latest epinio version(githubRelease)
	Condition:
		✔ [dockerImage] Check that splatform/epinio-installer:{{ source "epinio" }} is published(dockerImage)
		✔ [dockerImageContainer] Check that splatform/epinio-installer is used in Helm chart epinio(yaml)
	Target:
		⚠ [helm-chartss]  Update epinio version in chart epinio(helmChart)

```

**Version**

- OS: Linux
- Updatecli version: 0.17.0

**Additional context**
/

**Comment by olblak** [comment]
Well, the issue is a bit different, targets defined in pullrequest don't check if the target id exist or not.
A second improvement would be to always the display pulllrequest information and not only when in debug mode

**Comment by dduportal** [comment]
Sorry @olblak , I don't understand what happens? Could you share the manifest to allow reproduction?

**Comment by dduportal** [comment]
Sounds like it's related to #423 somehow (the loop at https://github.com/updatecli/updatecli/blob/730efa181c416af42015652c6c9faf9c502322e3/pkg/core/pipeline/pullRequests.go#L94-L107 does not seem to behave as expected) no ?

**Comment by olblak** [comment]
My updatecli configuration was wrong.
It was 

```pullrequests:
  helm-charts:
    kind: "github"
    scmID: "helm-charts"
    targets:
      - "helm-chartsSSSS"
    spec:
      labels:
        - "dependencies"
        - "epinio"
```
Instead of 
```
pullrequests:
  helm-charts:
    kind: "github"
    scmID: "helm-charts"
    targets:
      - "helm-charts"
    spec:
      labels:
        - "dependencies"
        - "epinio"
```
Please note the difference in the targets settings.
I missing validation for pullrequests.<id>.targets, where the value represent a list of targetID which should exist

**Comment by olblak** [comment]
So it's a different issue than https://github.com/updatecli/updatecli/issues/423
While the current issue is easy to solve, the other one requires more thinking.

**Comment by olblak** [comment]
> While the current issue is easy to solve, the other one requires more thinking.

Ha no, I have to open another issue than the one I just spot :p
