### ISSUE TITLE
Regression in 0.17.0: retrieved changelog is empty when generating the pull request body message

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#423]
**Describe the bug**

Check the folloiwng PR: https://github.com/jenkins-infra/kubernetes-management/pull/1831
If you click to expand the "Changelog" section, you will see ... an empty block.

**Steps to Reproduce**

This PR was originated by the following manifest:

The output of updatecli was the following:

```
############################################
# BUMP JENKINS-INFRA HELMFILE DOCKER IMAGE #
############################################

SOURCES
=======

lastRelease
-----------
Searching for version matching pattern "latest"
✔ Github Release version "1.6.2" found matching pattern "latest"

CHANGELOG:
----------
Release published on the 2021-12-20 17:21:59 +0000 UTC at the url https://github.com/jenkins-infra/docker-helmfile/releases/tag/1.6.2

<!-- Optional: add a release summary here -->
* [updatecli] [kubectl] Update version (#44) @jenkins-infra-bot

CONDITIONS:
===========
checkPodTemplate
----------------
✔ Key "spec.containers[0].name", in YAML file "PodTemplates.yaml", is correctly set to "helmfile"

checkDockerImage
----------------
✔ jenkinsciinfra/helmfile:1.6.2 available on the Docker Registry

TARGETS
========

updateImage
-----------
⚠ Key 'spec.containers[0].image', from file '/tmp/updatecli/jenkins-infra/charts/PodTemplates.yaml', was updated from 'jenkinsciinfra/helmfile:1.6.0' to 'jenkinsciinfra/helmfile:1.6.2'

PULL REQUESTS
=============

Pull Request available on:

	https://github.com/jenkins-infra/kubernetes-management/pull/1831
```

**Expected behavior**

I would have expected the changelog block, in the resulting pull request, to have the changelog content:

````markdown
## Changelog

<details><summary>Click to expand</summary>

```
Release published on the 2021-12-20 17:21:59 +0000 UTC at the url https://github.com/jenkins-infra/docker-helmfile/releases/tag/1.6.2

<!-- Optional: add a release summary here -->
* [updatecli] [kubectl] Update version (#44) @jenkins-infra-bot
```

</details>
````

**Screenshots**

**Version**
- OS: linux, macOS
- Updatecli version: 0.17.0

**Additional context**

* It's a regression introduced by updatecli 0.17.0: can't reproduce with 0.16.1
* Running with an attached debugger, I got the following results:
** When the instruction in charge of rendering the tempate is executed (e.g. https://github.com/updatecli/updatecli/blob/730efa181c416af42015652c6c9faf9c502322e3/pkg/plugins/github/pullrequest.go#L137), the attribute `p.Description` is an empty string.

**Comment by dduportal** [comment]
Moaaar debug:

* https://github.com/updatecli/updatecli/blob/730efa181c416af42015652c6c9faf9c502322e3/pkg/plugins/github/pullrequest.go#L93 => changelog is empty
* https://github.com/updatecli/updatecli/blob/730efa181c416af42015652c6c9faf9c502322e3/pkg/core/pipeline/pullRequests.go#L123 => `pr.Changelog` is an empty string
* https://github.com/updatecli/updatecli/blob/730efa181c416af42015652c6c9faf9c502322e3/pkg/core/pipeline/pullRequests.go#L108 => `changelog` is empty

It means that the loop https://github.com/updatecli/updatecli/blob/730efa181c416af42015652c6c9faf9c502322e3/pkg/core/pipeline/pullRequests.go#L94-L107 does not behave as expected.

**Comment by olblak** [comment]
I was just on my way to open this bug :p as I faced exactly the same issue on https://github.com/epinio/helm-charts/pull/46

**Comment by dduportal** [comment]
Moooar debug:

* https://github.com/updatecli/updatecli/blob/730efa181c416af42015652c6c9faf9c502322e3/pkg/core/pipeline/pullRequests.go#L94 => the loop never runs because `successTargetIDs` is an empty slice.
* https://github.com/updatecli/updatecli/blob/730efa181c416af42015652c6c9faf9c502322e3/pkg/core/pipeline/pullRequests.go#L75 is where this variables is set

**Comment by dduportal** [comment]
The core of this issue is that only the "successful" targets are checked for a changelog.

But if a target changed a file, than it's result is not `result.SUCCESS` but `result.ATTENTION`.

**Comment by dduportal** [comment]
PR opened with the fix.
