### ISSUE TITLE
Updatecli tries to open a pullrequest even if nothing changed

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#431]
**Describe the bug**
Updatecli tries to open a pull request even if nothing changed.
This issue was first identified on [asciidoctor/docker-asciidoctor](https://github.com/asciidoctor/docker-asciidoctor/runs/4613040569?check_suite_focus=true#step:6:183
)
This problem is related to https://github.com/updatecli/updatecli/issues/424

**Steps to Reproduce**
Run a updatecli pipeline configured to open a Github Pull Request which contains no change so the working branch doesn't exist on the remote location.

**Expected behavior**
We shouldn't try to open a pull request when the branch doesn't exist in the remote location
We should try to open a pull request if a change is detected between the remote branch and the remote target branch

**Screenshots**
[](https://github.com/asciidoctor/docker-asciidoctor/runs/4613040569?check_suite_focus=true#step:6:183)

**Version**

- OS: linux
- Updatecli version: v0.17.1

**Additional context**

**Comment by dduportal** [comment]
This issue is currently preventing all of the jenkins-infra's job to use updatecli at all.

We have disabled updatecli for now.

**Comment by olblak** [comment]
> This issue is currently preventing all of the jenkins-infra's job to use updatecli at all.
> 
> We have disabled updatecli for now.

:( Indeed the best workaround atm is to roll back to a previous version.
I have very limited spare time at the moment to work on a fix.

**Comment by dduportal** [comment]
> > This issue is currently preventing all of the jenkins-infra's job to use updatecli at all.
> > We have disabled updatecli for now.
> 
> :( Indeed the best workaround atm is to roll back to a previous version. I have very limited spare time at the moment to work on a fix.

No problem, I wrote the previous message as informational for the jenkins-infra, but it was written too quickly.

I'll have some time to dedicate on this specific problem: let me take care of that, I'll hand over if I'm stuck.

Thanks for your efforts and work buddy!
