### ISSUE TITLE
How can I get a target modification depending on another actual target modification?

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#433]
In the case of a manifest with different sources like [this one](https://github.com/jenkins-infra/helm-charts/blob/752db2670552080f5ba3fbb659bb3e7d3dab3697/updatecli/updatecli.d/uplink.yaml), how can I apply the chart bump (second target) only if the docker image version has been bumped?

Currently, if the docker image version doesn't change, the chart version is still bumped while there isn't any modification to it.
Example: https://github.com/jenkins-infra/helm-charts/pull/58/files

**Comment by olblak** [comment]
The short answer is there is no way at the moment to trigger a target A only if target B changed. This has to be handled at the condition level. I refrained to implement it 😄 .

In this specific case, is there any reason to not use the target of kind "helmChart" [doc](https://www.updatecli.io/docs/resources/helm_chart/)? It takes care for you to bump the chart Version when need, the appVersion if you configure and it cleanup the requirements file if needed.

**Comment by lemeurherve** [comment]
> In this specific case, is there any reason to not use the target of kind "helmChart" doc? 

- didn't wanted to make unnecessary requests as the source file or the retrieved version is in the same repository
- `versionincrement` didn't worked ¯\_(ツ)_/¯

**Comment by olblak** [comment]
> didn't wanted to make unnecessary requests as the source file of the retrieved version is in the same repository anyway

I am not sure to understand your point. [Here](https://github.com/olblak/epinio-helm-chart/blob/07a64f9edbcbe5a1b28f128240f90a67c668e40a/updatecli/updatecli.d/epinio.yaml) is a recent example of that workflow

> versionincrement didn't worked ¯_(ツ)_/¯

Then there is a bug because I used it version v0.17.0 quite a week or so

**Comment by olblak** [comment]
This a pullrequest generated by the updatecli which bump the appversion and the chart version
https://github.com/epinio/helm-charts/pull/46/files

**Comment by dduportal** [comment]
As per https://github.com/jenkins-infra/helm-charts/pull/83, this issue is not relevant anymore.
