### ISSUE TITLE
Feature Request: Better resource validation

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#466]
### Is your feature request related to a problem?

A general issue when writing updatecli manifest is validating input. At the moment the validation is done within the code. I am interested to find a better way to validate and therefore looking for

* [cuelang](https://cuelang.org/docs/integrations/yaml/)
* [validator](https://github.com/go-playground/validator)

### Anything else?

I really love this new way of submitting feature request.

**Comment by dduportal** [comment]
Could you describe a bit more what you want to achieve? I'm not sure to understand what do you mean?

**Comment by olblak** [comment]
> Could you describe a bit more what you want to achieve? I'm not sure to understand what do you mean?

I have been wondering for a while about the best way to validate user inputs, when we write updatecli manifest. 
At the moment we usually create a function named `Validate` where we define the different scenarios such as [here|https://github.com/updatecli/updatecli/blob/7db31b2fc0f0236cb4536eb42f4e402435dee7bd/pkg/plugins/file/main.go#L48].
The current way of validating user input is working so I more seeing this issue as a placeholder but maybe there is a better location (excepted my head to keep track of those experimentations)

**Comment by lemeurherve** [comment]
I'll explain my use of github projects to dump ideas out of your head if you want :)

**Comment by olblak** [comment]
I am closing this PR as we now have a first draft of a jsonschema
