### ISSUE TITLE
Add a `mergeMethod` parameter to the pull request spec

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#492]
> I am still missing the ability to set the merge type like rebase/squash/merge

I think changing `merge_method` to `squash` or `rebase` in addition  to auto-merge should do the trick: https://docs.github.com/en/rest/reference/pulls#merge-a-pull-request

For this a `mergeMethod` parameter could be added to the pull request spec (in another PR?)

_Originally posted by @lemeurherve in https://github.com/updatecli/updatecli/issues/491#issuecomment-1024111811_

**Comment by olblak** [comment]
I am targeting the milestone 0.20.0 as the PR is now ready.
@dduportal
