### ISSUE TITLE
Feature Request: Switch from MIT license to Apache v2

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#513]
### Is your feature request related to a problem?

When I started updatecli, I didn't bother too much about the license used within the project.
I wanted to use a permissive one so I choose MIT. But this decision triggered a lot of questions 
Now that I am having more and more contributions to the project, I am wondering if it wouldn't be better to switch Apache2.

[Apache-2.0](https://choosealicense.com/licenses/apache-2.0/)
[MIT](https://choosealicense.com/licenses/mit/)
 

### Alternatives you've considered

I considered more restrictive licenses model such as GPLv3 but I am concerned that it could be a blocker for contributing to updatecli

**Comment by lemeurherve** [comment]
> if it wouldn't be better to switch Apache2.
Any specific arguments again MIT or in favor of Apache 2?

**Comment by olblak** [comment]
> > if it wouldn't be better to switch Apache2.
> 
> Any specific arguments against MIT or in favor of Apache 2?
> 
> > more restrictive licenses model
> 
> Same kind of question, why?

because all the new project that I follow use the Apache license. Apache license seems to protect against patent use and trademark.
