### ISSUE TITLE
Feature Request: no stage: git-clone all the time

### ISSUE THREAD

**Issue by smerle33** [updatecli/updatecli#518]
### Is your feature request related to a problem?

I would like to have a way not to have a stage: git-clone all the time. As for example an updatecli file with just regexp on distant files that I'd like to check on local computer, can trigger a API rate limit for github and I have to wait an hour to be able to try again .....

### Solution you'd like

no git-clone except if really needed

### Alternatives you've considered

having a king of local switch that disable git-clone

**Comment by dduportal** [comment]
That feature will be easy to handle once #465 is done.

The idea will be to only clones the SCMs when needed (instead of "always at the beginning").

**Comment by dduportal** [comment]
> As far as I know, git clone

Over HTTPS, yes it is under the API rate limit. It's only with SSH-based clone that it's not.
