### ISSUE TITLE
yaml issue with file contain unicode character

### ISSUE THREAD

**Issue by sileht** [updatecli/updatecli#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I update file with yaml plugins I got an unexpected changes to the yaml file, like:

```
-      - name: Build 🔧 & Test 🔍
+      - name: "Build \U0001F527 & Test \U0001F50D"
```

The `key` spec was not updating this yaml attribute.

### Expected Behavior

Unicode characters are not replaced by their binary representation.
The line should not be updated.

### Steps To Reproduce

Edit a yaml file containing emoji.

### Environment

```markdown
- OS: archlinux
- updatecli:

Application:	0.19.2
Golang     :	1.17.6 linux/amd64
Build Time :	2022-02-04T08:32:54Z
```

**Comment by olblak** [comment]
Thanks @sileht for reporting this.
updatecli relies on go-yaml to manipulate YAML file and the issue seems to be related to https://github.com/go-yaml/yaml/issues/737
