### ISSUE TITLE
Feature Request: Gitea Integration 

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#523]
### Is your feature request related to a problem?

Many people reach out to me asking questions about Gitea integration for handling the scm and pullrequest resource.
The SCM should be quite similar to Github. 
The pull request could be managed by the gitea SDK available on https://gitea.com/gitea/go-sdk

**Comment by lemeurherve** [comment]
I'd take a look at https://github.com/jenkins-x/go-scm

> A small library with minimal depenencies for working with Webhooks, Commits, Issues, Pull Requests, Comments, Reviews, Teams and more on multiple git provider:
> 
>     [GitHub](https://github.com/jenkins-x/go-scm/blob/master/scm/driver/github/github.go#L46)
>     [GitHub Enterprise](https://github.com/jenkins-x/go-scm/blob/master/scm/driver/github/github.go#L19) (you specify a server URL)
>     [BitBucket Server](https://github.com/jenkins-x/go-scm/blob/master/scm/driver/stash/stash.go#L24)
>     [BitBucket Cloud](https://github.com/jenkins-x/go-scm/blob/master/scm/driver/bitbucket/bitbucket.go#L20)
>     [GitLab](https://github.com/jenkins-x/go-scm/blob/master/scm/driver/gitlab/gitlab.go#L19)
>     [Gitea](https://github.com/jenkins-x/go-scm/blob/master/scm/driver/gitea/gitea.go#L22)
>     [Gogs](https://github.com/jenkins-x/go-scm/blob/master/scm/driver/gogs/gogs.go#L22)
>     [Fake](https://github.com/jenkins-x/go-scm/blob/master/scm/driver/fake/fake.go)

**Comment by olblak** [comment]
Thanks @lemeurherve for the suggestion, @garethjevans made that suggestion too a while ago. And I think it's now time to look into it :p

**Comment by lemeurherve** [comment]
Also worth a look (?), the original repo: https://github.com/drone/go-scm

**Comment by olblak** [comment]
> Also worth a look (?), the original repo: https://github.com/drone/go-scm

When if I remember correctly, it wasn't maintained anymore which seems to be the case now
