### ISSUE TITLE
Target is executed even if one condition is failing 

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run `updatecli apply --config updatecli/updatecli.d/epinio.yaml  --debug --values updatecli/values.yaml` on the updatecli repository from https://github.com/olblak/epinio-helm-chart
I get  
```
REPORTS:


⚠ EPINIO.YAML:
	Sources:
		✔ [epinio] Get Latest epinio version (kind: githubRelease)
	Condition:
		✗ [dockerImage] Check that ghcr.io/epinio/epinio-server:0.2.1 is published (kind: dockerImage)
		✔ [dockerImageContainer] Check that ghcr.io/epinio/epinio-server is used in Helm chart epinio (kind: yaml)
	Target:
		⚠ [helm-charts] Update epinio version in chart epinio (kind: helmChart)



Run Summary
===========
Pipeline(s) run:
  * Changed:	1
  * Failed:	0
  * Skipped:	0
  * Succeeded:	0
  * Total:	1


```

### Expected Behavior

I am expecting the pipeline to be skipped as it used to be.
```
REPORTS:


⚠ EPINIO.YAML:
	Sources:
		✔ [epinio] Get Latest epinio version (kind: githubRelease)
	Condition:
		✗ [dockerImage] Check that ghcr.io/epinio/epinio-server:0.2.1 is published (kind: dockerImage)
		✔ [dockerImageContainer] Check that ghcr.io/epinio/epinio-server is used in Helm chart epinio (kind: yaml)
	Target:
		-  [helm-charts] Update epinio version in chart epinio (kind: helmChart)



Run Summary
===========
Pipeline(s) run:
  * Changed:	0
  * Failed:	0
  * Skipped:	1
  * Succeeded:	0
  * Total:	1
```

### Steps To Reproduce

When I run `updatecli apply --config updatecli/updatecli.d/epinio.yaml  --debug --values updatecli/values.yaml` on the updatecli repository from https://github.com/olblak/epinio-helm-chart

### Environment

```markdown
- OS: Linux
- updatecli: v0.19.2 and master branch
```

**Comment by olblak** [comment]
The last working version is 0.18.2

**Comment by olblak** [comment]
Seems to be introduced by https://github.com/updatecli/updatecli/pull/470/

**Comment by dduportal** [comment]
Good catch, that explains the failing golang 0.17.7 PRs \o/ Sorry for breaking the behavior: let me push a fix for this right now. 

Target milestone: 0.19.3

**Comment by olblak** [comment]
Thanks for looking into it, I would target 0.20.0
