### ISSUE TITLE
Validating "FILE" is displayed too often

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

SOURCES
=======
Validating "UPDATECLI.YAML"

githubSemver
------------
Searching for version matching pattern "~0.1"
✔ Git tag "0.1.2" found matching pattern "~0.1"
Validating "UPDATECLI.YAML"

gitExample2
-----------
ERROR: ✗ no tag found
Validating "UPDATECLI.YAML"

gitExample1
-----------
Searching for version matching pattern "latest"
✔ Git tag "v0.20.1" found matching pattern "latest"
Validating "UPDATECLI.YAML"

githubRegex
-----------
Searching for version matching pattern "v0.*"
✔ Git tag "v0.20.1" found matching pattern "v0.*"

CONDITIONS:
===========
Validating "UPDATECLI.YAML"

### Expected Behavior

In the current state, VALIDATING is displayed each time we re-evaluate a template which is done after each source
I would like to only show VALIDATING once at the beginning of a run

### Environment

```markdown
- OS: Linux
- updatecli: v0.20.1
```

**Comment by lemeurherve** [comment]
[My fault](https://github.com/updatecli/updatecli/pull/537) sorry, will try to find a fix or workaround
