### ISSUE TITLE
No username/password when username and password are specifed for dockerDigest

### ISSUE THREAD

**Issue by btrepp** [updatecli/updatecli#593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When specifying 

```
sources:
  registry:
    kind: dockerDigest
    spec:
      image: "alpine"
      tag: "latest"
      architecture: arm64
      password: gibberish
      username: a
```

The updatecli will complain that a username and password are not provided

```
registry
--------
WARNING: No username/password specified: trying to retrieve a token as anonymous user might not be supported or could impact the rate limiting on your network.

```

### Expected Behavior

updatecli uses username and password when provided

### Steps To Reproduce

Specify dockerDigest with username and password
run `updatecli diff`

Get error/warning that password/username is missing when supplied, and also fail to have auth.

Note: I discovered this when trying to use a private registry. I assume if credentials are being ignored I won't be able to use private registries until fixed.

### Environment

```markdown
- OS:
- updatecli:


updatecli version

VERSION

Application:    0.22.1
Golang     :    1.17.8 linux/amd64
Build Time :    2022-03-15T12:40:09Z
```

Note: this is a lie too, as this is running on an arm machine. So amd64 being reported is a different bug?
```


### Anything else?

It probably would be great if the examples/docs are updated. They seem pretty out-of-date with current behaviour. It's unclear is username and password or token are the go, but neither seem to work. So unsure what has been deprecated and what is the correct way to get the latest image version

**Comment by dduportal** [comment]
Hello @btrepp , thanks for reporting!

The reproduction example is good enough for me to reproduce and I've located the bug: incoming bug fix.

Do you mind opening a separate issue about the incorrect CPU architecture as it is another topic please? (it will also give us time to start an ARM64 instance to test :D)

**Comment by dduportal** [comment]
Release [v0.22.2](https://github.com/updatecli/updatecli/releases/tag/v0.22.2) is being released with the bug fix.

**Comment by btrepp** [comment]
Thanks for the amazingly quick release. Have raised the seperate issues s #599
