### ISSUE TITLE
File not found in source

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While working on https://github.com/jenkins-infra/docker-inbound-agents/pull/29 I wanted to retrieve Maven version from another repository, more specifically https://github.com/jenkins-infra/jenkins-infra/blob/production/hieradata/common.yaml.

To do so, I tried [to add another `scms` with the corresponding values](https://github.com/jenkins-infra/docker-inbound-agents/blob/4bfcb20bc937202dba1189478c5e0da2dc476727/updatecli/updatecli.d/maven.yml#L14-L32), but it failed to find the common.yaml file:
```
$ updatecli diff --config ./updatecli/updatecli.d --values ./updatecli/values.yaml --debug


+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli/updatecli.d/maven.yml"

SCM repository retrieved: 2
DEBUG: stage: git-clone

DEBUG: stage: git-clone

DEBUG: cloning git repository: https://github.com/jenkins-infra/docker-inbound-agents.git in /var/folders/z6/xykmq_m902n_7v4j8sxhzkdm0000gn/T/updatecli/jenkins-infra/docker-inbound-agents
Enumerating objects: 880, done.
Counting objects: 100% (270/270), done.
Compressing objects: 100% (115/115), done.
Total 880 (delta 181), reused 202 (delta 145), pack-reused 610
fetching remote branchesEnumerating objects: 137, done.
Counting objects: 100% (115/115), done.
Compressing objects: 100% (70/70), done.
Total 137 (delta 67), reused 85 (delta 45), pack-reused 22
DEBUG: cloning git repository: https://github.com/jenkins-infra/jenkins-infra.git in /var/folders/z6/xykmq_m902n_7v4j8sxhzkdm0000gn/T/updatecli/jenkins-infra/jenkins-infra
Enumerating objects: 21120, done.
Counting objects: 100% (750/750), done.
Compressing objects: 100% (104/104), done.
Total 21120 (delta 695), reused 667 (delta 646), pack-reused 20370
fetching remote branchesEnumerating objects: 5729, done.
Counting objects: 100% (5729/5729), done.
Compressing objects: 100% (3190/3190), done.
Total 5729 (delta 4400), reused 3601 (delta 2434), pack-reused 0


++++++++++++
+ PIPELINE +
++++++++++++



######################
# BUMP MAVEN VERSION #
######################


SOURCES
=======

getMavenVersionFromVMTemplate
-----------------------------
DEBUG: stage: git-checkout

DEBUG: checkout branch "updatecli_", based on "production" to directory "/var/folders/z6/xykmq_m902n_7v4j8sxhzkdm0000gn/T/updatecli/jenkins-infra/jenkins-infra"
DEBUG: branch 'updatecli_' doesn't exist, creating it from branch 'production'
DEBUG: branch "updatecli_" successfully created
ERROR: ✗ the yaml file "hieradata/common.yaml" does not exist
Pipeline "Bump Maven version" failed
Skipping due to:
        sources stage:  "the yaml file \"hieradata/common.yaml\" does not exist"
```

Note: the newly created branch has "updatecli_" as name (?)

### Expected Behavior

A working manifest, what else? ☕ 

### Steps To Reproduce

With this manifest:
```yaml
title: "Bump Maven test version"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"
  VMTemplate:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: jenkins-infra
      repository: jenkins-infra
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: production

sources:
  getMavenVersionFromVMTemplate:
    kind: yaml
    name: Get the latest Maven version set in VM template
    scmid: VMTemplate
    spec:
      file: hieradata/common.yaml
      key: "profile::buildmaster::default_tools.maven.mvn.version"
```
(And even with only the `VMTemplate` scm)

Test:
```bash
updatecli diff --config ./updatecli/updatecli.d --values ./updatecli/values.yaml --debug
```

### Environment

```markdown
- OS: macOS
- updatecli: v0.25.0
```

### Anything else?

As a workaround, I switched [to a source of `kind: file`, and the raw URL of the file](https://github.com/jenkins-infra/docker-inbound-agents/blob/164c0b3bb320652a538d3a44d79b2c8cacdbd123/updatecli/updatecli.d/maven.yml#L19-L22). 
I had to use a regexp instead of a yaml selector, but as a benefit, retrieving the file with this method is less resource intensive than the github one.

**Comment by olblak** [comment]
It's surprising that it appears now, considering how common this workflow is... :/
After a quick look it appears that we don't handle relative links https://github.com/updatecli/updatecli/blob/2a863606a828838eddfd4c8027ac997b7366ca65/pkg/plugins/resources/yaml/source.go#L18 like we do for files.

I think this issue will be solved once we finish and merge this PR https://github.com/updatecli/updatecli/pull/650/files
@lemeurherve Do you remember what's missing there? The PR is still in draft mode but if I remember correctly it was ready to be merge.

**Comment by olblak** [comment]
I tested with version 0.72.0 and everything is working as it expected
