### ISSUE TITLE
Blank lines removed from YAML target after apply

### ISSUE THREAD

**Issue by gionn** [updatecli/updatecli#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When declaring a yaml file as target, after a successful apply, every blank line in that yaml file get removed.

### Expected Behavior

No changes to the formatting of existing yaml files.

### Environment

```markdown
- OS: MacOS 12.5
- updatecli: v0.29.0
```

### Anything else?

While empty lines in yaml are meaningless and it's fine to get rid of them, they are often used as a separator to increase the human readability and updatecli is impairing that with the cleanup of the entire yaml document after each apply.

Example [here](https://github.com/Alfresco/alfresco-ansible-deployment/pull/395/files#diff-7be6987d456ad921f461608b488a7593f037ba8fc6e43ed862c903e91109c00a)

**Comment by olblak** [comment]
Thanks for reporting this issue, that part dependes on https://github.com/go-yaml/yaml
I had a quick look and it appears that they are different encoding option available. I need to investigate

**Comment by olblak** [comment]
Note for myself, I am currently migrating the yaml resource to a new library that fix many limitation but not this one.
It still removes empty line

**Comment by mcwarman** [comment]
@olblak https://github.com/goccy/go-yaml/pull/412

**Comment by olblak** [comment]
This issue is solved with https://github.com/updatecli/updatecli/pull/2949
Thanks, @mcwarman, for following this long awaited issue

We are targeting Updatecli version 0.86.0
