### ISSUE TITLE
pullRequests.go fails with panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by strangelookingnerd** [updatecli/updatecli#836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creation of Pull Request fails in `Apply` phase with `runtime error: index out of range [0] with length 0`. See log output:

```
PULL REQUESTS
=============

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/updatecli/updatecli/pkg/core/pipeline.(*Pipeline).RunPullRequests(0xc000c40370)
	/home/runner/work/updatecli/updatecli/pkg/core/pipeline/pullRequests.go:48 +0x1b37
github.com/updatecli/updatecli/pkg/core/pipeline.(*Pipeline).Run(0xc000c40370)
	/home/runner/work/updatecli/updatecli/pkg/core/pipeline/main.go:234 +0x3ce
github.com/updatecli/updatecli/pkg/core/engine.(*Engine).Run(0x3c565e0)
	/home/runner/work/updatecli/updatecli/pkg/core/engine/main.go:250 +0x57c
github.com/updatecli/updatecli/cmd.run({0x246dd90?, 0x0?})
	/home/runner/work/updatecli/updatecli/cmd/root.go:89 +0x3c6
github.com/updatecli/updatecli/cmd.glob..func1(0x3c2cf20?, {0x246c652?, 0x4?, 0x4?})
	/home/runner/work/updatecli/updatecli/cmd/apply.go:30 +0x11b
github.com/spf13/cobra.(*Command).execute(0x3c2cf20, {0xc000626440, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x3c2c7a0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/updatecli/updatecli/cmd.Execute()
	/home/runner/work/updatecli/updatecli/cmd/root.go:42 +0x65
main.main()
	/home/runner/work/updatecli/updatecli/main.go:8 +0x17
```

### Expected Behavior

Action used to work fine with release `0.30.0` and started to fail with  `0.31.0` as well as  `0.32.0`.

### Steps To Reproduce

See https://github.com/jenkinsci/custom-folder-icon-plugin/actions/runs/2960947456

### Environment

```markdown
- OS: Ubuntu latest
- updatecli: v0.32.0 and v0.31.0
```

### Anything else?

Maybe I am missing something but the changelogs do not indicate any change that would cause my configuration to become malformed or incompatible.

**Comment by olblak** [comment]
Thanks for opening this issue, I recently added the Gitea support and so did some refactoring in the pullrequest section to simplify its configuration. I'll try to replicate this issue

**Comment by olblak** [comment]
well this one was a very stupid one :/ thanks again for reporting. I'll probably trigger a release tomorrow

**Comment by strangelookingnerd** [comment]
No harm no foul, thanks for the quick response and fix!
