### ISSUE TITLE
dockerimage authentioncation issues.

### ISSUE THREAD

**Issue by samj1912** [updatecli/updatecli#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When providing a `token` to the dockerimage it doesn't use the provided token. 

Additionally, for docker registries like artifactory, the default username/password mechanism used by updatecli doesn't seem to work either in authenticated mode or in anonymous mode.

```
DEBUG: Searching tags for the image "registry.io/namespace/name"
DEBUG: Retrieving a bearer token from https://registry.io/token?scope=repository:namespace:pull&service=registry.io with the username  and the associated password.
WARNING: No username and/or password specified: trying to retrieve a token as anonymous user might not be supported or could impact the rate limiting on your network.
DEBUG: Emitting a request to https://registry.io/token?scope=repository:namespace:pull&service=registry.io
ERROR: Got an HTTP response code 404 while logging in to the registry registry.io.
ERROR: ✗ Got an HTTP response code 404 while logging in to the registry registry.io.
```

### Expected Behavior

That the above works.

### Steps To Reproduce

Create a manifest like so - 

```yaml
sources:
  test:
    kind: dockerimage
    spec:
      image: myregistry.io/test/test
      token: 'test'
```

### Environment

```markdown
- OS: macos
- updatecli: 0.33.2
```

**Comment by samj1912** [comment]
I would generally suggest moving to https://github.com/google/go-containerregistry which powers quite a few popular OCI image manipulation tools.

It has amazing support for quite a few features that I see are currently explicitly implemented in updatecli - features like authentication, listing repositories, fetching digests etc.

OCI/Docker registries can be a pain to deal with because of the disparity in terms of the spec they follow. GGCR has been battle-tested with tools like buildpacks, cosign, kyverno, ko, apko and tons of other production OCI related tools.

**Comment by olblak** [comment]
Hi,
That's a good suggestion, the container code base grew up to mutch and we may benefits to move this library. I'll have a look to see how much effort would be needed

**Comment by olblak** [comment]
I had a look to the [go-containerregistry](https://github.com/google/go-containerregistry/tree/main/pkg/authn) and it would be a huge improvement. It's not clear to me if you are interested @samj1912 to look into this.

I guess we would start on https://github.com/google/go-containerregistry/tree/main/pkg/authn

**Comment by samj1912** [comment]
I am interested and familiar with GGCR. I will try to submit a PR when I get time but it might take a couple of weeks. Otherwise, if some contributor gets to it before me, please let me know in this issue.

**Comment by samj1912** [comment]
@olblak I added some initial code at #900 although I have manually tested it, I don't know how much time I will have to add any additional tests. PTAL and feel free to take over.
