### ISSUE TITLE
Feature Request: Add Docker Image Tag to Docker Image Digest

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#999]
### Is your feature request related to a problem?

In the autodiscovery feature, I would like to be able to automatically detect the next Docker Image Digest for a specific tag.
While oci registry do not allow this query, I recently discovered that we a digest can be specified next to a tag such as  

- `updatecli/updatecli:v0.38.0@sha256:e420b84349f75cb25ca7fe88ec510afa418a0aec7d3d8e639e337669a377099d`

### Solution you'd like

I propose that the docker digest resource also include the tag in the answer

**Comment by dduportal** [comment]
Nice FR! This feature should allow user to opt-out though, for cases with a non OCI-compliant registry.

(see the Docker Engine 20.10 that has a fallback mechanism with a warning: the opt-out could be shown with a WARNING when enabled)
